### ISSUE TITLE
Add support for zone transfers and wildcard domains

### ISSUE THREAD

**Issue by OJ** [OJ/gobuster#1]
With the new DNS feature we currently blindly brute force the DNS names in the word list to see what resolves. This is a pointless exercise when:
- [Wildcard records](https://en.wikipedia.org/wiki/Wildcard_DNS_record) are in use.
- [Zone transfers](https://en.wikipedia.org/wiki/DNS_zone_transfer) are possible.

We should cater for both of these prior to running the brute force, and exit early if needs be. This is effectively what `fierce` does.

**Comment by invisiblethreat** [comment]
I forked this morning to write this, and then discovered that I know a lot less about Go than I hoped. :( https://github.com/invisiblethreat/offensive-security/blob/master/wildcard_domain.py

```python
import uuid
import socket
import sys

prefix = uuid.uuid4()
domain = sys.argv[1]

try:
  result = socket.gethostbyname(str(prefix) + "." + domain)
  print "%s has a wildcard DNS entry" % sys.argv[1]

except:
  print "%s does not have a wildcard DNS entry" % sys.argv[1]
```

**Comment by OJ** [comment]
For wildcard entries, detecting them is at least the first step. If a wildcard entry is found I think the sensible thing to do is bail out.

Zone transfers shouldn't be too bad though :)

**Comment by OJ** [comment]
The wildcard stuff has been done in https://github.com/OJ/gobuster/pull/10

**Comment by OJ** [comment]
Wildcard stuff updated in https://github.com/OJ/gobuster/commit/0d43d75890008d7f9eaa2b30f98b2acf7504eed9
