### ISSUE TITLE
Allow to choose a custom resolver

### ISSUE THREAD

**Issue by BastienFaure** [OJ/gobuster#102]
Hi dude,

I am currently benchmarking many DNS tools and I like this one :) I did not find any option to specify a custom DNS resolver. This may be useful especially if the system resolver has limitations, and targeting another would bring much more speed.

Thanks !

**Comment by FireFart** [comment]
I found a way to implement a custom DNS resolver, but it does not work on windows.

The following example can be used to set a custom DNS resolver and also a Timeout
```go
func customDialer(ctx context.Context, network, address string) (net.Conn, error) {
	fmt.Println("test")
	d := net.Dialer{}
	return d.DialContext(ctx, "udp", "8.8.8.8:53")
}

func main() {
	r := net.Resolver{
		PreferGo:     true,
		Dial:         customDialer,
	}
       // set a timeout for DNS requests
	ctx, cancel := context.WithTimeout(context.Background(), time.Millisecond)
	defer cancel()
	ipaddr, err := r.LookupIPAddr(ctx, "www.example.com")
	if err != nil {
		fmt.Println("ERROR")
		fmt.Println(err)
	} else {
		fmt.Println(ipaddr)
	}
}
```

On windows go always uses the C implementation so we can not force our custom DNS server and that's odd :/
https://golang.org/pkg/net/#hdr-Name_Resolution

**Comment by BastienFaure** [comment]
Oh man that's a sad story!

**Comment by FireFart** [comment]
I implemented it in this PR:
https://github.com/OJ/gobuster/pull/104

**Comment by FireFart** [comment]
Already live
