### ISSUE TITLE
Unstable wildcard detection

### ISSUE THREAD

**Issue by BastienFaure** [OJ/gobuster#103]
Hi dude,

My domain `faure.io` has a wildcard configured to resolve on 163.172.255.227. I tried to run `gobuster` with a very restricted wordlist (only two entries: `bo` and `test`). I ran the tool twice, and got two different results:
```
$ gobuster -i -m dns -w wlist -t 10 -u faure.io

=====================================================
Gobuster v2.0.1              OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dns
[+] Url/Domain   : faure.io
[+] Threads      : 10
[+] Wordlist     : wlist
=====================================================
2018/09/23 18:32:39 Starting gobuster
=====================================================
Found: bo.faure.io [163.172.255.227]
Found: test.faure.io [163.172.255.227]
=====================================================
2018/09/23 18:33:34 Finished
=====================================================
```
```
$ gobuster -i -m dns -w wlist -t 10 -u faure.io

=====================================================
Gobuster v2.0.1              OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dns
[+] Url/Domain   : faure.io
[+] Threads      : 10
[+] Wordlist     : wlist
=====================================================
2018/09/23 18:33:54 Starting gobuster
=====================================================
2018/09/23 18:33:54 [-] Wildcard DNS found. IP address(es): 163.172.255.227
2018/09/23 18:33:54 [!] To force processing of Wildcard DNS, specify the '-fw' switch.
=====================================================
2018/09/23 18:33:54 Finished
```

When I then ran the tool with the `-fw` switch, the wildcard seem to be always detected. 

Thank you!

**Comment by FireFart** [comment]
Hi @BastienFaure,
i tried the command several times with version 2.0.1 and it always detects the wildcard. Currently this works by generating a new uuid and requesting this as a subdomain on the target domain (https://github.com/OJ/gobuster/blob/0e209e5f5c91b33823e6680f4498b0c31737c397/gobusterdns/gobusterdns.go#L19). If this call returns an IP adress it marks the domain as wildcard domain.

So there is an edge case when this detection fails we assume the IP was not resolved and continue without checking the error. I think we have to look into checking that error in the Setup function.

**Comment by BastienFaure** [comment]
Yes that makes sense. I first thinked that my router was the problem (he has very low DNS performance when used as resolver), so used 8.8.8.8 as resolver, and still the same result.
Is there a timeout in resolution ?

**Comment by FireFart** [comment]
Maybe there is a timeout but we can not set it. Go directly calls the operation system DNS resolve function (https://golang.org/pkg/net/#hdr-Name_Resolution) and returns an error if this fails. I think the returned error can also be a timeout or smth else instead of "host not found" but there is currently no clean way of checking the error on go. We would have to do a string matching on the retuned error message :/

**Comment by BastienFaure** [comment]
Ok, got the reason by adding debug and retrying several times:

```
2018/09/23 19:38:38 lookup 533007f9-f54a-4560-99cc-07b944a5c8ef.faure.io on 192.168.1.1:53: read udp 192.168.1.19:57574->192.168.1.1:53: i/o timeout
```
It's definitely a corner case. I'll let you know how you want to manage this side-effects: maybe adding a second check, or retry at timeout...
Thanks

**Comment by FireFart** [comment]
I think implementing this would cause the code to get too complex for this little corner case, sorry
