### ISSUE TITLE
Add command line option for port specification.

### ISSUE THREAD

**Issue by neitrinoweb** [OJ/gobuster#105]
Something like usual -p or add a feature to specify the port in the URL scheme.

**Comment by FireFart** [comment]
you can use -u http://url:port/path . Does this work for you?

**Comment by OJ** [comment]
As @FireFart says, just put the port in the URL. This definitely works ;)

**Comment by OJ** [comment]
I should probably shove this somewhere in the readme ;)

**Comment by cocoonkid** [comment]
Oh yes please!  That would be great. I struggled for 20 minutes wondering :smile_cat:

**Comment by aymanemontassir** [comment]
@cocoonkid  Thanks man!
