### ISSUE TITLE
How fantasical would it be for a target list include ?

### ISSUE THREAD

**Issue by n0x00** [OJ/gobuster#11]
# VERY fantastical.

Is it possible to have a list of target addresses (such as nmap's -iL)

I'll buy you steak next time your in London -_-

**Comment by OJ** [comment]
IMHO, this doesn't make sense for `url` mode, but makes a bit more sense for `dns` mode.

However, given that everything is multithreaded, making the output "nice" would be painful. So would you be open to just having it all come out as a mess that you can grep through or are you expecting me to compartmentalise the output for you?

Bro, Y U NO PR?! :dancer:

**Comment by n0x00** [comment]
but what about when I do big list from ASN's and have a big ass list of https://ip:port/$derping_here 
:( 

#FINE 

you can have sausages.

it's all good mate, if it's too much ballache for my niche criteria ... I'll give it a miss ... or pick up some go books hehe

**Comment by OJ** [comment]
Let me know if you feel like answering my question :)

**Comment by n0x00** [comment]
I'd be more happy to get it in any format! :cake: :cake: :cake:

**Comment by pentesticles** [comment]
Optimus - Don't succumb to peer pressure. He says steak, he means McDonald's. I've been burned by this before. But just to stir the pot, may input parsing would be a nice feature on this - you told me you were a scalertron.

**Comment by OJ** [comment]
Screw you both and your trolling! :)

Adding this isn't so difficult, but doing it _nicely_ isn't as simple as it looks on the surface. For each word that you process you not only have multiple extensions but you now have multiple targets. Each target has its own set of issues, including whether the target is even online or not. Given that the targets are being processed concurrently along with the words in the dictionary, you start to get into the murky waters of managing errors across threads and cleaning up nicely. There are ways around this, but they're not obvious.

There's just nuances that aren't known until you dive in. So while it sounds simple, I reckon it's more than a 5 minute job.

> Maybe he doesn't know how

I know what you're trying to do!

**Comment by pentesticles** [comment]
Hahahahaha! I knew you'd bite! 

Just messing with your Optimus - if anyone can bust it out, it's you. Nice suggestion though from John ;-) 

Lawrence

**Comment by OJ** [comment]
Been thinking about this a lot, and I think that the answer is going to remain "no" for now, I'm sorry. Going to close this. If it becomes a super big issue, then let's talk again. I think the effort vs gains at the moment isn't enough to justify. However, if you feel like submitting a PR, go for it :)
