### ISSUE TITLE
Feature Request For Gobuster

### ISSUE THREAD

**Issue by ericnyamu1** [OJ/gobuster#112]
hey,

Gobuster is just what the doctor ordered but it would be nice if we could be able to port scan the found subdomains when in dns mode.I think it would be nice to have an option to port scan and print only hostnames that have open ports on them.That way feeding the results to tools like Eyewitness or SubOver would be a breeze.

**Comment by JoelPagliuca** [comment]
Or maybe a **suggested** nmap command instead?
nmap is very prevalent for port scanning, my opinion is building port scanning functionality is basically reinventing the wheel :P

**Comment by FireFart** [comment]
sorry but I don't think we will ever implement this - Gobuster is an enumeration tool. If you want to invoke other steps you need to write a bash script or smth. to run nmap against the found hosts.

**Comment by OJ** [comment]
+1 to @FireFart's comment. This really has no relation to what the tool was designed to do. There are other tools that already do this, and do it better than we ever will.
