### ISSUE TITLE
Feature request: http2 support

### ISSUE THREAD

**Issue by noraj** [OJ/gobuster#113]
I would be great to have http2 support on gobuster else the tool is limited into auditing http1.1 server.

**Comment by OJ** [comment]
Good call. We should look into this for sure.

**Comment by FireFart** [comment]
Is this still a problem with todays go version or is HTTP2 already implemented? I Currently have no http2 only server to try this out.

**Comment by FireFart** [comment]
Looks like it's not enabled by default, we need to use a http2.Transport on the http client instead. But the main problem here is finding out if the server supports http2

**Comment by OJ** [comment]
Maybe we should add it as an option, so that users can say "I want it" via the command line.

**Comment by FireFart** [comment]
https://golang.org/pkg/net/http/

```
Starting with Go 1.6, the http package has transparent support for the HTTP/2 protocol when using HTTPS.
```

**Comment by noraj** [comment]
Seems it's only for HTTPS and not HTTP.

**Comment by FireFart** [comment]
https://en.wikipedia.org/wiki/HTTP/2#Encryption

**Comment by noraj** [comment]
![image](https://user-images.githubusercontent.com/16578570/85206588-75373100-b323-11ea-9832-c9c94cd8bdde.png)

**Comment by FireFart** [comment]
yes but read the wikipedia article. No one uses http2 over plaintext so it's basically non existent

**Comment by noraj** [comment]
> so it's basically non existent

On client side (by web browser) but server side the web server may serve http/2 over HTTP.

**Comment by FireFart** [comment]
we will not reimplement the http2 protocol inside gobuster sorry. If you feel golang should add support for plaintext http2 feel free to open an issue at https://github.com/golang/go/issues
