### ISSUE TITLE
Feature Request: Filter responses by size

### ISSUE THREAD

**Issue by chppppp** [OJ/gobuster#114]
When bruting webservers that perform wildcard responses it can be useful to filter responses by size to not get false positives on whatever the wildcard response is. 

One day I will pick up the Go book and try to submit a PR but until then let this issue be a reminder for myself! 

Thanks

**Comment by nikhilj2se** [comment]
count me in, just starting learning go :)

**Comment by FireFart** [comment]
This is already included in the `v3.1-cleaned` branch: https://github.com/OJ/gobuster/blob/v3.1-cleaned/cli/cmd/dir.go#L155
