### ISSUE TITLE
Feature Request: Color results by respone code

### ISSUE THREAD

**Issue by eranchetz** [OJ/gobuster#115]
For example: 
2xx - green 
3xx - yellow
4xx - red 

we can use [aurora](https://github.com/logrusorgru/aurora) Sprintf [ResultToSring].(https://github.com/OJ/gobuster/blob/5ca1584c160e417bc7f7364f00bf3e756b0b2f25/gobusterdir/gobusterdir.go#L84)
@OJ wdyt? is that the proper place to implement it?

**Comment by jaikishantulswani** [comment]
> For example:
> 2xx - green
> 3xx - yellow
> 4xx - red
> 
> we can use [aurora](https://github.com/logrusorgru/aurora) Sprintf [ResultToSring].(
> 
> [gobuster/gobusterdir/gobusterdir.go](https://github.com/OJ/gobuster/blob/5ca1584c160e417bc7f7364f00bf3e756b0b2f25/gobusterdir/gobusterdir.go#L84)
> 
> Line 84 in [5ca1584](/OJ/gobuster/commit/5ca1584c160e417bc7f7364f00bf3e756b0b2f25)
> 
>  func (d GobusterDir) ResultToString(g *libgobuster.Gobuster, r *libgobuster.Result) (*string, error) { 
> )
> @OJ wdyt? is that the proper place to implement it?

@eranchetz Is that working ?

**Comment by eranchetz** [comment]
@jaikishantulswani I was hoping for a response before implementing, I will test it later this week and update.

**Comment by eranchetz** [comment]
@jaikishantulswani https://github.com/OJ/gobuster/pull/122

**Comment by jaikishantulswani** [comment]
Thank you @eranchetz  :)

**Comment by OJ** [comment]
Thanks folks. Yes there's a PR open for it, but needs a little bit more work before it can be landed. Cheers!

**Comment by firefart** [comment]
This is implemented on the `dev` branch for now
