### ISSUE TITLE
Additional details output files

### ISSUE THREAD

**Issue by BastienFaure** [OJ/gobuster#116]
Hi!
Currently, (from my point of view) the output file contains only requested words and return codes:

```
$ cat gobuster.out
/admin (Status: 302)
/include (Status: 302)
/test (Status: 302)
```
I think that writing the full path would make output files more useful. Also, writing the command line and/or the hour would be useful.

I was thinking about something like:
```
$ cat gobuster.out
[Tue Nov 20 16:09:16 CET 2018] gobuster -u http://example.com/path -w /path/to/wordlist -m dir -t 50
http://example.com/path/admin (Status: 302)
http://example.com/path/include (Status: 302)
http://example.com/path/test (Status: 302)
```

What do you mind ? Maybe writing the exact same output than on the CLI would also be fine !

**Comment by OJ** [comment]
You need to specify the `-e` flag for extensive output. That should solve
your problem.

**Comment by BastienFaure** [comment]
Oh sorry, I searched the option but haven't seen this switch :)

**Comment by OJ** [comment]
No problem. Thank you! 😁
