### ISSUE TITLE
 dial udp 1.1.1.1:53: socket: too many open files

### ISSUE THREAD

**Issue by serialfuzzer** [OJ/gobuster#128]
Here is a screenshot of the error gobuster is throwing:
![gbi](https://user-images.githubusercontent.com/22111782/53288031-c673f680-37a9-11e9-8274-b331ccdf37c1.png)

I have researched about the issue in [stackoverflow](https://stackoverflow.com/questions/32325343/go-tcp-too-many-open-files-debug) and [other places](https://github.com/cloudflare/cloudflared/issues/20) but nothing seems to be working.

**Comment by flacostec** [comment]
Had the same issue, had to lower the number of thread. You could also to ulimit -n 8096.

**Comment by OJ** [comment]
Interesting. I wonder if there's a way of getting the agent to cache DNS results rather than relying on the OS to do it. I'll try to dig deeper into this.

**Comment by OlivierLaflamme** [comment]
Lower your number of threads instead of doing `-t 50` go and `-t 10` this fixed the issue for me

**Comment by shelld3v** [comment]
To fix this, we need to increase the limit of open files (by default, it is `1024`)

>#### Edit `/etc/security/limits.conf`
>One option to up the limit is to edit `/etc/security/limits.conf` so that it includes the two lines below.
>
>- `*` represents all users
>- `hard` and `soft` indicate the hard and soft limits for the OS
>- `nofile` is the number of open files option.
>```
>/etc/security/limits.conf
>-------------------------
>...
>*        soft nofile 4096
>*        hard nofile 8192
>...
>```
>#### Use `ulimit` directly
>A faster option, that is not persistent, is to simply use the `ulimit` command to change the setting.
>```
>ulimit -n 4096
>```

**Comment by firefart** [comment]
jeah you need to either increase the system limits or lower the threads when this happens.
