### ISSUE TITLE
 Invalid certificate: x509: certificate has

### ISSUE THREAD

**Issue by g0rx** [OJ/gobuster#129]
Invalid certificate: x509: certificate has expired or is not yet valid

how to fix ?

**Comment by OJ** [comment]
Where is that error coming from? Is this when you're gobusting a site that has an invalid certificate? If so, please read the [README](https://github.com/OJ/gobuster/blob/master/README.md), you'll see there's a `-k` flag to disable certificate checks.

**Comment by psyray** [comment]
Hi,

@OJ 

Agree with you, but why this flag is not in the --help ?
More simple no ? And this is the first place people looks ;)

```
# gobuster --help                                                                
Usage:
  gobuster [command]

Available Commands:
  dir         Uses directory/file brutceforcing mode
  dns         Uses DNS subdomain bruteforcing mode
  help        Help about any command
  vhost       Uses VHOST bruteforcing mode

Flags:
  -h, --help              help for gobuster
  -z, --noprogress        Don't display progress
  -o, --output string     Output file to write results to (defaults to stdout)
  -q, --quiet             Don't print the banner and other noise
  -t, --threads int       Number of concurrent threads (default 10)
  -v, --verbose           Verbose output (errors)
  -w, --wordlist string   Path to the wordlist
```

```
# apt-cache policy gobuster                           
gobuster:
  Installed: 3.0.1-0kali1
  Candidate: 3.0.1-0kali1
```

**Comment by Envincion** [comment]
thats was smooth thanks bro

**Comment by Abu-Sagidolla** [comment]
> Where is that error coming from? Is this when you're gobusting a site that has an invalid certificate? If so, please read the [README](https://github.com/OJ/gobuster/blob/master/README.md), you'll see there's a `-k` flag to disable certificate checks.

Thanks bro so much

**Comment by manuelarte** [comment]
The option is still there, but I can't find it in the README anymore.
