### ISSUE TITLE
POST Support

### ISSUE THREAD

**Issue by Rhynorater** [OJ/gobuster#131]
Gobuster is the best directory bruteforcer around, IMHO. However, there are two features I would love to see. One is a dream, the other is something that I believe should be implemented.

1. POST Support
It would be really helpful for us to be able to supply a verb for the request. This would allow us to find lots of additional content only listed in POST requests. It would also be great to say "do both GET and POST"
2. Recursive option
I realize this goes against what gobuster stands for, but I think it would be a great feature for people with different needs.

I'd like to put a bounty of a $5 on the POST request feature (since someone already has a POST request) and a bounty of $15 on the recursive feature. Bounty will be paid when code is pushed to main branch

Thanks again for such a great product!
Justin

**Comment by OJ** [comment]
Hi Justin,

Thanks for the message. The specification of other verbs is something that's in the works to be honest. There's a more general case that we're keen to catch as well, so expect that to happen.

Recursion isn't as easy as it sounds for a number of reasons, and I am yet to put a post together about it to explain why. I might get on that today! From there at least we can all have a discussion about it.

As far as bounties go, I do appreciate the gesture, however we don't accept donations. If you're interested in supporting the project in any way, you can make use of our [OpenCollective ](https://github.com/OJ/gobuster/wiki#open-collective-history) project where we accept donations from the community and pass the funds on to charity.

Cheers again mate, I love the constructive discussion that people invest in this project. It's humbling and flattering to have good people invest their time. Watch this space, we do have a lot more coming!

OJ

**Comment by tiyeuse** [comment]
Hi !
I'm wondering if this issue is still considered and if the possibility of choosing the VERB can be implemented ?
I definitely think this options should be interesting (not only POST but also arbitrary methods).

Thank you for this great tool !
Tiyeuse

**Comment by OJ** [comment]
@tiyeuse yeah I'm keen to get this support in too. It's definitely on the cards!

**Comment by FireFart** [comment]
@tiyeuse if you use the `v3.1-cleaned` branch you can use already custom verbs and POST requests
