### ISSUE TITLE
Add support for bruteforcing discovered subdirectories

### ISSUE THREAD

**Issue by JamesWestbrook7** [OJ/gobuster#136]
Hey OJ and team, thanks for the fantastic tool. I would love to see support added for automatically bruteforcing discovered subdirectories using the same wordlist that was fed in.

**Comment by OJ** [comment]
Hi James. You're asking for support for recursion, which is a pretty hot topic and has been requested a fair bit in the past already. I am still yet to write my rationale as to why gobuster doesn't support this feature.

At this point, I don't have a plan to add it. I'm still talking to @FireFart behind the scenes about it, so it's not 100% off the cards. It just comes with a considerable number of issues.

Thanks, but will close this for now. I appreciate your time! All the best.
