### ISSUE TITLE
Unable to Connect

### ISSUE THREAD

**Issue by BigB86** [OJ/gobuster#143]
Hello,

  I'm currently running Gobuster v2.0.1 on kali all updated. Gobuster was working about a week ago, but now it seems that no matter what site I try to use it against I get an error. This is the error I keep getting.
```
gobuster -u https://subdomain.site.com -s 200,302 -w /root/tools/paths.txt

unable to connect to https://subdomain.site.com/: Get https://subdomain.site.com/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
I've confirmed that the website is up and running perfectly fine. I've even tried extending the timeout to no avail.

Thanks!

**Comment by FireFart** [comment]
The error message says this is a connection timeout. Are you behind a proxy?

**Comment by BigB86** [comment]
No I'm not behind a proxy. Just a straight connection to my home router.

**Comment by FireFart** [comment]
Then try the site via curl or intercept the requests using a proxy like burp to investigate this issue. There is nothing we can do here in code if your clients fails to connect to the target

**Comment by BigB86** [comment]
I was already pentesting the website with Burp Suite without a problem. What issue am I trying to investigate with Burp? The website loads without issue within my browser.

**Comment by FireFart** [comment]
The reason I mentioned burp is so you can see the request and whats going on. You need to investigate the problem on your machine if you're asking for help. So try to play around with the timeout parameter and see what's going on with wireshark and burp

**Comment by IftequarIffu** [comment]
> The error message says this is a connection timeout. Are you behind a proxy?

What to do if I'm behind a proxy ?

**Comment by PauDina18** [comment]
Error: error on running gobuster: unable to connect to http://10.129.203.194/: Get "http://10.129.203.194/": dial tcp 10.129.203.194:80: connect: no route to host

Can anyone help me with this error?
