### ISSUE TITLE
Delay option?

### ISSUE THREAD

**Issue by Athrekas** [OJ/gobuster#147]
Hello, I'd like to know if it's possible to set a delay per request, or at least knowing what the default delay is.

For example on dirsearch I can do "-t 3 -s 0.350" (3 threads, 350 miliseconds per request).

Thank you very much.

**Comment by FireFart** [comment]
Hi,
no currently not but we could implement it (at least per thread)

**Comment by Athrekas** [comment]
Awesome! Thank you for the quick response!

**Comment by FireFart** [comment]
Sorry this was closed by accident by merging. The reverted implementation does not really work so we need to implement a sleep per thread here

**Comment by FireFart** [comment]
this will be released in the next version as a `--delay` parameter
