### ISSUE TITLE
Gobuster Does Not Print Lengths

### ISSUE THREAD

**Issue by ngkogkos** [OJ/gobuster#150]
Hi,

Great job on releasing version 3 of GoBuster! I am trying to use it for general fuzzing as well to see if it suits my needs. Not sure if this is a valid issue or not, so please pardon me if it's my bad.

It seems like gobuster does not print response lengths in the below configuration:

![image](https://user-images.githubusercontent.com/1519209/59888396-5d9b3480-93bf-11e9-86b1-62fe53c0d234.png)

I've even checked with 200 codes and it doesn't show them.

Could you please look into this?

**Comment by OJ** [comment]
Thanks for the report @ngkogkos I'm looking into this right now.

**Comment by OJ** [comment]
Definitely a regression. Not sure how that happened. Fixing. Thank you!

**Comment by OJ** [comment]
Fixed in https://github.com/OJ/gobuster/commit/9ef3642d170d71fd79093c0aa0c23b6f2a4c1c64 thank you for the report. 3.0.1 has been released now with the fix in it. Thank you @ngkogkos.

**Comment by FireFart** [comment]
mea culpa. Thanks for fixing it @OJ !
