### ISSUE TITLE
Bruteforce files with no extension

### ISSUE THREAD

**Issue by nsrauf** [OJ/gobuster#155]
Hi,

Is it possible to find the files that have no extension?

e.g -x php,html only find file.php or file.html but how can we match files like changelog, readme, todo etc.

Thanks!

**Comment by OJ** [comment]
Hi @nsrauf by default, gobuster will use the word in the wordlist without appending anything.

For example if you wordlist contains:
```
foo
bar
```
Then it'll request:
```
http://site.com/foo
http://site.com/bar
```

If you add extensions, such as `-x php,html` it'll request these:
```
http://site.com/foo
http://site.com/foo.php
http://site.com/foo.html
http://site.com/bar
http://site.com/bar.php
http://site.com/bar.html
```

If you add the `-f` option, which forces the use of slashes, it'll do this instead:
```
http://site.com/foo/
http://site.com/bar/
```

Hope that helps!
OJ

**Comment by nsrauf** [comment]
Thanks @OJ - Any plans to add the recursive feature ?
