### ISSUE TITLE
Extension without a dot

### ISSUE THREAD

**Issue by AlessandroZ** [OJ/gobuster#157]
Hi, 

I wanted to add an extension without a dot (for example: `~`) but it's not possible. 

```
gobuster dir -u host -x .html -w wordlist
```

is indentical as:

```
gobuster dir -u host -x html -w wordlist
```

I'm not familiar with go but I have noticed that the dot is removed from the user input [here](https://github.com/OJ/gobuster/blob/master/helper/helper.go#L22) and a new one is added [here](https://github.com/OJ/gobuster/blob/master/gobusterdir/gobusterdir.go#L149).

I think you should let the user input as it is and let the user the choice to add a dot or not. 

Thanks for your tool. 

Have a nice day.

**Comment by FireFart** [comment]
an extension has a `.` per definition. If you want to add something to the single wordlist items you can modify it outside of gobuster and pass it via stdin or use the `pattern` feature on the `v3.1-cleaned` branch
