### ISSUE TITLE
Feature Request: randomized user-agent

### ISSUE THREAD

**Issue by mzpqnxow** [OJ/gobuster#161]
Similar to `sqlmap`, a flag like `--random-agent` that tells `gobuster` to choose from a list of known real User-Agent values. I think in general that few people really want `gobuster/$VERSION` as their user-agent, and it is annoying have to look up a valid User-Agent value and make a shell alias or manually specify it each run

This is mainly useful when conducting penetration testing or some other type of security assessment where you don't want to be caught by very rudimentary IDS. The load is noisy of course, but I've already seen at least one SOC/IDS set up to fire specifically on `^User-Agent: gobuster.*` header

This one seems pretty easy and the list of user agent values can probably be taken directly from `sqlmap`. The only choice to make is whether to embed it inside `gobuster` or include it as a separate file. I would argue it's best to include built into the `gobuster` executable, with an optional flag to specify a list provided by the user on the filesystem

This is another one I can make a PR for, but my time is short and I have two other issues I would like to get to first.

Let me know what you think

Thx

**Comment by vitorfhc** [comment]
Any updates?

**Comment by mzpqnxow** [comment]
Looks like this was fixed, thx
