### ISSUE TITLE
[Feature Request] Detect Forward Slash

### ISSUE THREAD

**Issue by ngkogkos** [OJ/gobuster#162]
Hello!

Current version of gobuster has an option to ` -f, --addslash                      Apped / to each request` but it seems to me that it auto-appends the forward slash to requests anyway. Please see screenshots below where the list I used uses no forward slashes.

![image](https://user-images.githubusercontent.com/1519209/61176393-02242700-a5b8-11e9-8c40-7996af2ca7ef.png)
![image](https://user-images.githubusercontent.com/1519209/61176395-04868100-a5b8-11e9-841b-463ee5343d6f.png)

If I use a list with forward slashes by default, it will come with double ones:

![image](https://user-images.githubusercontent.com/1519209/61176404-40b9e180-a5b8-11e9-92d8-f57f49f8dcaf.png)

This is not a big issue, but it would be nice if gobuster could auto-detect when slashes are in place and either 1) prompt/warn the user to decide if it should keep 1 '/' only or 2) let it be (as there may be cases where it could make sense).

If users are warned, it would also be nice to have an argument that removes duplicate slashes, although I am not sure how easy to implement this would be.

**Comment by FireFart** [comment]
Hi,
the `-f` option appends the slash at the end of the URL/directory. The only slash that is appended autoamtically is between the domain and the directory.
For the double slash please see the discussion here https://github.com/OJ/gobuster/pull/121. We agreed that these transformations should occur outside of gobuster as you might want to have double slashes in your tests
