### ISSUE TITLE
unable to specify url

### ISSUE THREAD

**Issue by quad02** [OJ/gobuster#164]
I used the same command for gobuster every time i used it and it worked fine gobuster -u URL -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -r -t 30 but then i had an issue that said Error: unknown command "30" for "gobuster" so i tried multiple other numbers and methods such ass --threads=number -t=number but still same issue so then i was like fine ill get rid of that flag then and then i got an error that said Error: unknown shorthand flag: 'u' in -u so i was like okay well maybe they changed the flags so i did the --help and there is no flag to specify the url and the thread flag is still the same but it wont work please fix this because this is one of my most used tools and its very frustrating for it to not work

**Comment by FireFart** [comment]
The syntax has changed in version 3. Please refer to the Readme in this Repository or use `gobuster help`

**Comment by quad02** [comment]
i did check the help page and if it wasn't for a htb team member i would've never of known i had to do gobuster dir -u url -w wordlist

**Comment by OJ** [comment]
https://github.com/OJ/gobuster#examples <~ it's right there, and has been since the 3.0.0 release.

**Comment by cutrightjm** [comment]
I agree with quad02 - you shouldn't have to consult the online docs to get the syntax.

**Comment by OJ** [comment]
> I agree with quad02 - you shouldn't have to consult the online docs to get the syntax.

Sorry, but the help is _inside_ the program **and** documented online. If you fail to find either of those I have no idea how I can help more.

**Comment by cutrightjm** [comment]
Would you mind pointing me to where it is inside the program? On my current program in Kali rolling, it isn't in "gobuster help"

**Comment by OJ** [comment]
Kali is still running an earlier version of Gobuster (2.x).

![image](https://user-images.githubusercontent.com/28896/83365234-2401e480-a3ea-11ea-803e-e10b85dd1fcd.png)

Documentation on this is in the history of the project. The interface changed in 3.x.
