### ISSUE TITLE
Bug:Linux Mint Command not found

### ISSUE THREAD

**Issue by n1ghty93** [OJ/gobuster#165]
Hey guys,
i cant use gobuster cause my linx mint only outputs
gobuster: command not found
i did made it from source and the path should be correct aswell cause the normal go commands are working without probs

**Comment by FireFart** [comment]
if you install it from source you need to run `go install` too to put in your gopath bin folder. If it's in your path you should be able to call it. Otherwise build it and run `./gobuster`

**Comment by OJ** [comment]
Hi @n1ghty93, @FireFart is right, you need to `go install` once you've built, and make sure you have `$GOPATH/bin` included in your `$PATH`.

Cheers.
