### ISSUE TITLE
Minor typo in help menu for "dir"

### ISSUE THREAD

**Issue by dazvid** [OJ/gobuster#166]
https://github.com/OJ/gobuster/blob/12a4785815e2683c1898041c5527cb3a90929221/cli/cmd/dir.go#L141

"Apped" should be "Append". Also appears in README.md.

Figured minor typo's aren't worth a PR. 🤷‍♀

**Comment by OJ** [comment]
Thanks @dazvid I've pushed the fix in https://github.com/OJ/gobuster/commit/d0547407440c5044a6131cc0cfb9e25bf490b133 but won't do a release until we get some more stuff sorted. Thanks for that!
