### ISSUE TITLE
dynamically linked v3.0.1

### ISSUE THREAD

**Issue by fopina** [OJ/gobuster#167]
The new 3.0.1 release is dynamically linked (even though it's a quite fatter binary)

```
/gobuster/gobuster-linux-amd64 # ls -lh gobuster
-rwxr-xr-x    1 root     root        5.6M Jun 21 00:16 gobuster
/gobuster/gobuster-linux-amd64 # ldd gobuster
        /lib64/ld-linux-x86-64.so.2 (0x7fb50e8df000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fb50e8df000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fb50e8df000)
```

The old 2.0.1 was static
```
/gobuster/gobuster-linux-amd64/gobuster-linux-amd64 # ls -lh gobuster
-rwxr-xr-x    1 root     root        4.0M Sep 11  2018 gobuster
/gobuster/gobuster-linux-amd64/gobuster-linux-amd64 # ldd gobuster
ldd: gobuster: Not a valid dynamic program
```

Is there a reason for it or was it an overlapse?
As I'm using it inside an alpine docker (no libc), I just want to know if I should switch base image or just re-compile it if there's nothing new that'll fail for being static

**Comment by fopina** [comment]
if anyone bumps into the same in the meantime, I've re-compiled the linux binary [here](https://github.com/fopina/gobuster/releases/tag/3.0.1p1)

**Comment by FireFart** [comment]
@OJ that's strange. Looks that behaviour changed in newer go versions. Looks like we need to add some more ldflags:
http://blog.wrouesnel.com/articles/Totally%20static%20Go%20builds/

**Comment by fopina** [comment]
I simply used the existing Makefile in OSX and Go 1.12.
Usually I use those flags mentioned in the post but didnt specify them this time...
