### ISSUE TITLE
Would be great to add inject point in dns enumeration

### ISSUE THREAD

**Issue by hdbreaker** [OJ/gobuster#168]
Will be great to have support for specific injection point (*) in DNS enumeration like:

gobuster dns -t 50 -d staging-*.target.com -w wordlist.txt

**Comment by hdbreaker** [comment]
I'm working in a fast patch that could add this functionality to gobuster dns bruteforcing process, I will be doing the PR in some hours!

**Comment by FireFart** [comment]
this is now possible on the `v3.1-working` branch using the `patterns` feature
