### ISSUE TITLE
Feature Request: Use Session Cookie from first Request

### ISSUE THREAD

**Issue by cost6** [OJ/gobuster#176]
Certain WAFs or webserver have an upper limit for sessions per IP. If multiple request without a session are sent, a new session is generated for each request. This leads to an exhaustion of sessions and the IP is "blocked" till the session pool is cleaned up.

This problem can be solved if the session generated for the first request is used in all subsequent requests.

A flag for the dir mode option for this would be very much appreciated.

**Comment by FireFart** [comment]
You can call the site manually and supply the cookie in the `cookie` parameter so gobuster will send it with every request. We can't include all cookied from the initial request as this could cause many problems, sorry
