### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by mohammadobaid1** [OJ/gobuster#179]
I tried various options for installing gobuster including building from source or directly using go get command since I have my go environment setup but I notice that everytime I tried to install , it throws me below error 
```
main.go:3:8: cannot find package "github.com/OJ/gobuster/v3/cli/cmd" in any of:
	/usr/local/go/src/github.com/OJ/gobuster/v3/cli/cmd (from $GOROOT)
	/home/muhammadobaid/work/src/github.com/OJ/gobuster/v3/cli/cmd (from $GOPATH)

```
Is there any seperate package which I need to install with ? I notice that v3 folder does not exist and may be that's why it is throwing such error !!

**Comment by kremlinkid** [comment]
Im having the same issue here. Can anyone pls chime in?

**Comment by FireFart** [comment]
What are the commands you have executed?

**Comment by mohammadobaid1** [comment]
I tried with go get command or directly building from source, in both cases same error pops up. I ended up running it via docker image which works for me

**Comment by FireFart** [comment]
Are you on the latest version of golang? Module support was introduced in 1.11 if you define an env variable. If you are not on the latest golang version please update and try again (go modules are currently enabled automatically). You can check your version with `go version`.

**Comment by mohammadobaid1** [comment]
I think that's the mistake I am doing. I am currently running on go 1.10. I will try it with 1.11
