### ISSUE TITLE
go inconsistent vendoring 

### ISSUE THREAD

**Issue by karthikkrs** [OJ/gobuster#183]
Trying to Install Gobuster and ge the following error 
![Screenshot from 2019-10-01 03-38-11](https://user-images.githubusercontent.com/4638408/65956280-dcf8c500-e3fe-11e9-8d7d-0254af735221.png)

Not sure where i am going wrong .  Some help would be much appreciated

**Comment by FireFart** [comment]
sorry, but we distribute no vendor/modules.txt files. Maybe try resetting the git branch?
