### ISSUE TITLE
Progress Request Count Visual Bug - Minor

### ISSUE THREAD

**Issue by ngkogkos** [OJ/gobuster#185]
Hello,

When gobuster shows progress for example `5 out of 500` it does not calculate the extra requests performed by added extensions.

So if I feed it with a wordlist of 10 files and give it 4 extra extension, it will still show:

```
1 out of 10
2 out of 10
...
```

instead of making the overall number of requests 50, so `1 out of 50`.

It's mainly a visual bug I think and doesn't matter much, but good for improvement.

**Comment by FireFart** [comment]
this is now fixed in the `v3.1-cleaned` branch
