### ISSUE TITLE
Multiple Domain list scan

### ISSUE THREAD

**Issue by attacker34** [OJ/gobuster#192]
Dear @OJ 

Please add support for a subdomains list to be bruteforced for directories. right now, only one domain can be bruteforced against directory's list.

Sincerely,

**Comment by its0x08** [comment]
That could be not bad actually!!
bulk and recursion is something that is missing at the time an its very needed !

1. Comma separated wordlists and domains(or file with multiple domainslike @attacker34 says)
3. And recursive dir searching and maybe recursive domain also

**Comment by firefart** [comment]
please use an external script to do this or a simple for loop.
