### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by sh1va73** [OJ/gobuster#193]
I have installed on a fresh Kali with command: go get github.com/OJ/gobuster
golang is already installed.
When I now type: gobuster I get a command not found error.
Any other steps I need to do to install?

**Comment by OJ** [comment]
On Kali you can just `apt install gobuster`

Don't forget to `go install github.com/OJ/gobuster` if you want to go from source.

**Comment by sh1va73** [comment]
Thanks on Kali its working now. I would like to install it on my Ubuntu machine as well.
Here I still get command not found error.

**Comment by OJ** [comment]
The latest versions of Ubuntu have it too!

**Comment by sh1va73** [comment]
I could not get it working on ubuntu but I manage now with command line: 
go run main.go dir -url mydoamin.com -w wordlist.txt

I would have preferred to run it with gobuster command, but this is ok as well.

**Comment by OJ** [comment]
Does `go install github.com/OJ/gobuster` not work?

**Comment by sh1va73** [comment]
I did get an error on that, but maybe I did it wrong.

**Comment by OJ** [comment]
Make sure you have the latest version of Go installed.

**Comment by Johnfarcy** [comment]
no, that particular command doesn't work- it says command not found

**Comment by isuru0x01** [comment]
I get the same error.

```
➜  Downloads go version
go version go1.17.6 linux/amd64
➜  Downloads go install github.com/OJ/gobuster/v3@latest                                         
go: downloading github.com/OJ/gobuster/v3 v3.1.0
go: downloading github.com/OJ/gobuster v2.0.1+incompatible
go: downloading github.com/spf13/cobra v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20200728195943-123391ffb6de
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/sys v0.0.0-20200810151505-1b9f1253b3ed
➜  Downloads gobuster dir -u 10.10.230.203 -w /usr/share/wordlists/dirb/common.txt      
zsh: command not found: gobuster
➜  Downloads ls
1.webp  go1.17.6.linux-amd64.tar.gz  isurumadusanka.ovpn  php-reverse-shell.php  VNC-Viewer-6.21.406-Linux-x64
➜  Downloads gobuster
zsh: command not found: gobuster
➜  Downloads 
```

**Comment by danieldt92** [comment]
Had the same problem with Ubuntu, but managed to fix it

If the system cannot find the "gobuster" command and you are using UBUNTU, it is likely that during the installation via "go install" the "go" folder was downloaded in to the wrong folder, maybe is something related to  how ubuntu manage environment vars, i really dont know, but

It should be located in /usr/local/go

Find where the gobuster download is and then move the directory tree to the correct path.
```

sudo find / . -type d -name '!o!j

<wrongDir>/go/pkg/mod/github.com/!o!j

mkdir /usr/local/go/
mv <wrongDir>/go/* /usr/local/go
```

**Comment by alexxriv** [comment]
thanks n3tty this solved for me. I installed go using homebrew and for some reason it created a /usr/local/go directory but at the same time it created another directory with the same name in my home dir.

**Comment by oscarsson444** [comment]
thank you n3ttyk, i followed your steps but had to manually move all the content in <wrongDir>/go/bin and <wrongDir>/go/pkg to /usr/local/go/bin and /usr/local/go/pkg respectively, since they already existed.
