### ISSUE TITLE
Installation failed because of the path not found 

### ISSUE THREAD

**Issue by roughiz** [OJ/gobuster#195]
When w try to simply install trough go get we have the error :

package github.com/OJ/gobuster/v3/cli: cannot find package "github.com/OJ/gobuster/v3/cli" in any of:

It's because all folder for installation gobusterdir etc are not in the right v3/ folder you have to move them like :+1: 

- mkdir v3
- mv gobusterdir gobusterdns gobustervhost helper libgobuster v3/
and now the installation works great.

Nota: do this modificion from repo in your $GOPATH

**Comment by FireFart** [comment]
This is because of your golang version. You need to use an up to date version with gomodules support
https://golang.org/doc/install
