### ISSUE TITLE
Test files inside of found directories

### ISSUE THREAD

**Issue by FabianTe** [OJ/gobuster#197]
Hi there,

quick though I came upon when I found a `log` folder using dirbuster. What about a mode / flag that searches for common files inside found directories? I'd like to describe an example of such a mode to explain what I'd like to see:

Let's assume the directory `log` has been found by the `dir` command. Given the command has been called with the `-file-probes` flag, gobuster probes for common file names. In the context of the found `log` folder that would be permutations of log file names generated by [log4php](https://logging.apache.org/log4php/docs/appenders/file.html) or [log4j](https://logging.apache.org/log4j/2.x/manual/appenders.html#FileAppender) and similar libraries.

I am unsure if this is a usefull feature to everybody but I think this would be an interesting functionality to test if files inside a directory are accessable.

What do you think of this idea?

**Comment by FireFart** [comment]
currently the only option is to restart gobuster with the new directory again. There is already an open issue for implementing recursion so that would fix that too
