### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with "\n"; err=<nil>

### ISSUE THREAD

**Issue by smaxx1337** [OJ/gobuster#198]
When trying to dirbust with gobuster, I get this error:
**2019/12/13 11:30:16 Unsolicited response received on idle HTTP channel starting with "\n"; err=<nil>**
(./gobuster dir -u http://obscurity.htb:8080 -w /usr/share/wordlists/dirb/common.txt)

It's gobuster v3.0.1 and I installed it by downloading the binary directly.

**Comment by FireFart** [comment]
Looks like this can happen if the server sends invalid http responses:
https://github.com/golang/go/issues/19895
