### ISSUE TITLE
apt-get install gobuster does not work

### ISSUE THREAD

**Issue by subbusecurity** [OJ/gobuster#199]
I am a novice. I am trying to install gobuster on Kali Linux, but it fails.

`root@kali:~# apt-get install gobuster
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  gobuster
0 upgraded, 1 newly installed, 0 to remove and 1154 not upgraded.
Need to get 2,019 kB of archives.
After this operation, 6,759 kB of additional disk space will be used.
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Get:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1 [2,019 kB]
Err:1 http://ftp.harukasan.org/kali kali-rolling/main amd64 gobuster amd64 3.0.1-0kali1
  File has unexpected size (990 != 2019032). Mirror sync in progress? [IP: 14.49.100.116 80]
  Hashes of expected file:
   - SHA256:4bf7525f25019212d2818e3ec2b805997339ae132c6311de518c93986b8277e7
   - SHA1:c7ecde7948dfd8d5d6bd25232b1625d9c152571a [weak]
   - MD5Sum:0bfe37e091dd2ba29673d92ed6cb616f [weak]
   - Filesize:2019032 [weak]
E: Failed to fetch http://ftp.harukasan.org/kali/pool/main/g/gobuster/gobuster_3.0.1-0kali1_amd64.deb  File has unexpected size (990 != 2019032). Mirror sync in progress? [IP: 14.49.100.116 80]
   Hashes of expected file:
    - SHA256:4bf7525f25019212d2818e3ec2b805997339ae132c6311de518c93986b8277e7
    - SHA1:c7ecde7948dfd8d5d6bd25232b1625d9c152571a [weak]
    - MD5Sum:0bfe37e091dd2ba29673d92ed6cb616f [weak]
    - Filesize:2019032 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

Any help in this regard?

**Comment by FireFart** [comment]
As the error message suggest, try update and run it again. If the error persists, open a bug on the kali bugtracker as this is no bug related to gobuster https://bugs.kali.org/
