### ISSUE TITLE
Where is executable?

### ISSUE THREAD

**Issue by g33xter** [OJ/gobuster#2]
Is it compiled or what? ![screenshot from 2015-05-15 06 13 03](https://cloud.githubusercontent.com/assets/8503135/7653307/a0e2fb62-fac9-11e4-80d8-fa1e2b67b202.png)

**Comment by OJ** [comment]
It's source code, you have to compile it yourself using the go compiler.

**Comment by g33xter** [comment]
Got it, thanks!!

**Comment by g33xter** [comment]
Getting this error?
![screenshot from 2015-05-15 06 27 48](https://cloud.githubusercontent.com/assets/8503135/7653567/8f2aa85a-facb-11e4-802c-8c6d7f8e627e.png)

**Comment by OJ** [comment]
Builds cleanly for me. Please make sure your development environment is set up correctly. The README contains links to the documentation which will help you get your go build environment set up.
