### ISSUE TITLE
Gobuster not working with connection reset

### ISSUE THREAD

**Issue by olivierlemoal** [OJ/gobuster#206]
I am auditing a network equipment with an ugly web server which reset connection instead of returning a 404 Not found when probing for a non existing resource. 
Gobuster does not seems to handle such case and fails :

``Error: error on running gobuster: Get http://192.168.1.27/5c3677c0-56e6-465a-bc9c-1554464e6c78: EOF``

Can the gobuster architecture easily handle this case ?

**Comment by FireFart** [comment]
sadly not. We can only detect the connection request but not why it happened. If we would treat a EOF as 404 this would cause a lot false positives when there is a real connection reset
