### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by kirtiso** [OJ/gobuster#207]
Hey,
When i'm using Gobuster having issue , i don't know how to resolve it please help 
@kali:~/go/bin$ ./gobuster dir -u https://buffered.io -w ~/wordlists/shortlist.txt
Error: error on parsing arguments: wordlist file "/home/kirti/wordlists/shortlist.txt" does not exist: stat /home/kirti/wordlists/shortlist.txt: no such file or directory

**Comment by ajdintrejic** [comment]
What does "cat /home/kirti/wordlists/shortlist.txt" return? Are you sure the file is there?

**Comment by FireFart** [comment]
as the error says, the wordlist you referenced does not exist. Please check the path to the wordlist and make sure that it exists and is readble
