### ISSUE TITLE
gobuster output is not as expected

### ISSUE THREAD

**Issue by VuNgocTan** [OJ/gobuster#209]
Hi, I got a problem with gobuster, I bruteforce it, but the result only index.html, result should be more, what am I missing here, or what can be the problem ? command I use:
`gobuster dir -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -u x.x.x.x -x html,txt -t 50`

**Comment by FireFart** [comment]
You need to intercept the reuqests with a proxy and look at the responses to see why it is failing.
