### ISSUE TITLE
syntax and usage is upside down

### ISSUE THREAD

**Issue by massimotamos** [OJ/gobuster#214]
Respect to the basic usage:

https://tools.kali.org/web-applications/gobuster

the new version requires some time to learn it, this makes the tool less intuitive to use.

The help should provide some common usage examples. The -u flag disappeared from the usage.

**Comment by OJ** [comment]
The new version adds one single parameter (which replaces the `mode` flag `-m`), other than that, it's the same.

If you're on version 2.x `-m` still exists. If you're on 3.0, it doesn't. Please read the README.
