### ISSUE TITLE
Error when I run a script with many subdomains

### ISSUE THREAD

**Issue by bonino97** [OJ/gobuster#221]
Hello!

I don't know if it is appreciated, but it is constantly giving me an error.

> : no such host)e.org[-] Unable to validate base domain: binance.org

This is the Syntax: 

> gobuster dns -d ${domain} -w ${gobusterDictionary} -t 70 -o GobusterResult.txt

All subdomains listed below if valid.

Could you confirm that it is my problem, or that I am doing something wrong?

![image](https://user-images.githubusercontent.com/24545141/79669600-060e5680-8193-11ea-95fe-051b30f08cbf.png)

Thank you :)

**Comment by bonino97** [comment]
The solution was .trim() at the subdomain called.

**Comment by nancheng12345** [comment]
Friend, I have the same problem as you but I still don't understand, can you share the complete code?
