### ISSUE TITLE
error while running GObuster

### ISSUE THREAD

**Issue by coopjab** [OJ/gobuster#222]
heiii
I'm having trouble in running gobuster.... i want to find directories in the hack the box ip addr and I'm connected through vpn 
i don't know y i get connection refused while I/m connected to vpn 
the screenshot of this problem is attached below
pls help me 
![2020-04-22 10_03_12-Kali - VMware Workstation](https://user-images.githubusercontent.com/36020960/80074898-7d633200-8567-11ea-932b-173ee8dae5de.png)

**Comment by coopjab** [comment]
can i get some answers pls its urgent

**Comment by FireFart** [comment]
As the error message says the target timed out. You can either increase your timeout or you need to investigate the problem on your machine by using a proxy or wireshark.
