### ISSUE TITLE
error in code.

### ISSUE THREAD

**Issue by Tasaddar12** [OJ/gobuster#224]
I only found this because my cat stepped on my keyboard. After the 4 key was pressed numerous times it caused some error to happen. I dont know much about code except basic coding. I will put a picture in here. I dont believe this is suppose to happen so I am posting it here as an issue. 
![gobuster_error_proof](https://user-images.githubusercontent.com/61332370/81316210-4c9bf600-9059-11ea-8d7c-03f926edd35a.PNG)

**Comment by FireFart** [comment]
Hi,
which version of gobuster are you running? Can you please paste the full stack trace of the error?

Thanks

**Comment by Tasaddar12** [comment]
I cant cause the error to happen again I am not very aware as for what caused this but I do know it is most up to date with apt-get. I can not get the full error back sorry I dont have any log for the error either. I was trying to stop my cat from stepping all on my keyboard when I look up I see this.

**Comment by harmjay** [comment]
Yes, it is. Use dirbuster, if something wrong.

**Comment by FireFart** [comment]
if you encounter this bug again, please post the whole output and stacktrace here. Going to close this until we can reproduce it
