### ISSUE TITLE
Feature Request: Support for URL Lists or NMAP/Nessus XML Processing?

### ISSUE THREAD

**Issue by twosevenzero** [OJ/gobuster#229]
Is there any interest in supporting a list of URLs to run gobuster against? I am also curious if you would be interested in allowing an nmap input file. Something like it parses the nmap.xml file for common web ports and kicks off the buster.

Currently when I want to run it against many urls, I throw it in a quick for loop. This is an ok approach but since gobuster traps the SIGINTs and returns a 0 I havent found a way to trap out of the loop.

**Comment by firefart** [comment]
jeah we can not implement every custom format thus the preferred way is to parse the files externally and run gobuster in a for loop with the correct url
