### ISSUE TITLE
Forgetting a url flag has incorrect help

### ISSUE THREAD

**Issue by John123Allison** [OJ/gobuster#231]
If you use Gobuster in dir mode and forget to provide a url flag, it tells you to add `-url` - however, the actual flag is `-u`

**Comment by FireFart** [comment]
```
root@61888fab8467:/opt/gobuster# gobuster dir
Error: required flag(s) "url", "wordlist" not set
```
`url` and `u` are both valid:
https://github.com/OJ/gobuster/blob/master/cli/cmd/http.go#L17

**Comment by John123Allison** [comment]
That's false, -url does not work locally.

**Comment by FireFart** [comment]
It’s ˋ—urlˋ with a double dash. You can alwaysconsult the help using ˋ—helpˋ

**Comment by John123Allison** [comment]
Ah thanks. My bad.
