### ISSUE TITLE
Feature Request: gobuster dir，Before detection, make sure that the random directory and file do not exist

### ISSUE THREAD

**Issue by hktalent** [OJ/gobuster#232]
Feature Request: gobuster dir
Before detection, make sure that the random directory and file do not exist, ensure the credibility of the status code, and then start detection
1、random path,file name
234lknh2k3hj4/23424s.jsp
now get status code is 404,not 200
2、now start check other cgi
if is 200, so it is exist

**Comment by OJ** [comment]
Wildcard detection already does this behind the scenes using GUIDs.

**Comment by FireFart** [comment]
That's already done here: https://github.com/OJ/gobuster/blob/master/gobusterdir/gobusterdir.go#L87
If a non existent file return the same output as the root site you will get the wildcard warning
