### ISSUE TITLE
Issue I have

### ISSUE THREAD

**Issue by timotiose** [OJ/gobuster#238]
verytime i use gobuster it come up with this error: 

2 errors occurred:
    * WordList (-w): Must be specified (use -w - for stdin)
    * Url/Domain (-u): Must be specified

this is the command im using:

gobuster dir -u http://<ip> -w /usr/share/dict/README.select-wordlist

<ip> has repleaced the ip in this case

**Comment by FireFart** [comment]
You are most probably running an old version of gobuster. Please refer to the readme how to get a current version installed
