### ISSUE TITLE
Add in the README.txt to export GOBIN env

### ISSUE THREAD

**Issue by thefishermanhacker** [OJ/gobuster#24]
http://stackoverflow.com/questions/18149601/go-install-always-fails-no-install-directory-outside-gopath
mkdir bin 
export GOBIN=$GOPATH/bin

**Comment by OJ** [comment]
Hi,

The README.txt currently states this:
```
Since this tool is written in Go you need install the Go language/compiler/etc. Full details of installation and set up can be found on the Go language website.
```
This text includes links on how to set up a working build environment. Reproduction of this information is not only unnecessary, but it opens the door for future inaccuracies when things change and don't get updated here.

Sorry, but my stance here is that setting up a Go build environment is the responsibility of the user, and I won't be documenting any information on that here until such times as the `gobuster` build process becomes non-standard.

Thanks!
