### ISSUE TITLE
Error: the DNS Server returned the same IP for every domain

### ISSUE THREAD

**Issue by 1UC1F3R616** [OJ/gobuster#241]
```bash
Error: the DNS Server returned the same IP for every domain. IP address(es) returned: XX.XX.XXX.XXX . To force processing of Wildcard DNS, specify the '--wildcard' switch
```
Is this error because it's no subdomain was found?

**Comment by OJ** [comment]
No this is because the domain that you're brute forcing has a wildcard domain entry which returns the same IP for every subdomain you query.

**Comment by 1UC1F3R616** [comment]
@OJ what can be done to in this case?
