### ISSUE TITLE
Got a segmentation fault while fuzzing vhosts

### ISSUE THREAD

**Issue by AlienX2001** [OJ/gobuster#246]
While pressing ^C(ctrl +c) instead of sigint got a sigsegv [
![Screenshot 2020-10-10 16:19:41](https://user-images.githubusercontent.com/64488123/95646454-53d29e80-0ae6-11eb-8dd1-5ff491d70a1e.png)
](url)

**Comment by FireFart** [comment]
Hi,
can you please try again with the latest version?
