### ISSUE TITLE
Add support to deal with wildcard dns

### ISSUE THREAD

**Issue by johnnyDEP** [OJ/gobuster#25]
Add in logic to send a couple random subdomain resolution requests and if they are the same IP ignore responses with that IP for future requests. I think fierce does something similar...

**Comment by OJ** [comment]
This feature already exists, as far as detection goes:
```
gobuster -m dns -u <redacted> -w ~/wordlists/subdomainsbig.txt

Gobuster v1.1                OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dns
[+] Url/Domain   : <redacted>
[+] Threads      : 10
[+] Wordlist     : /Users/oj/wordlists/subdomainsbig.txt
=====================================================
[-] Wildcard DNS found.
=====================================================
```

We send one fixed DNS request that is a GUID (currently hard-coded). If that comes back then there's clearly a wildcard.

I hadn't pondered the option of continuing to see if other IP addresses come out during the brute force. For the most part, I think it's fair to say that a wildcard DNS for a given domain will result in a lot of work for no gain, however I might just add an option to force the brute to continue and return entries that do not match that first IP.

Thanks for the suggestion.

**Comment by johnnyDEP** [comment]
That would be cool. I sometimes find myself going back to fierce just because of this option. Thanks for response and the work you put in to this.

**Comment by OJ** [comment]
@johnnyDEP Thanks for being a user :)

I'll aim to put some time into this over the next week. Cheers again!

**Comment by OJ** [comment]
@johnnyDEP how about this?
```
$ ./gobuster -w ~/wordlists/subdomainsbig.txt -u <redacted> -m dns

Gobuster v1.2                OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dns
[+] Url/Domain   : <redacted>
[+] Threads      : 10
[+] Wordlist     : /Users/oj/wordlists/subdomainsbig.txt
=====================================================
[-] Wildcard DNS found. IP address(es):  <redacted>
[-] To force processing of Wildcard DNS, specify the '-fw' switch.
=====================================================
$ ./gobuster -w ~/wordlists/subdomainsbig.txt -u <redacted> -m dns -fw

Gobuster v1.2                OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dns
[+] Url/Domain   : <redacted>
[+] Threads      : 10
[+] Wordlist     : /Users/oj/wordlists/subdomainsbig.txt
=====================================================
[-] Wildcard DNS found. IP address(es):  <redacted>
Found: email.<redacted>
^C[!] Keyboard interrupt detected, terminating.
=====================================================
```

**Comment by OJ** [comment]
@johnnyDEP changes can be tracked here by the way: https://github.com/OJ/gobuster/compare/v1.2?expand=1

**Comment by johnnyDEP** [comment]
Looks good thanks!

**Comment by OJ** [comment]
Merged into master :)
