### ISSUE TITLE
[FEATURE] Logging content-type on positive results

### ISSUE THREAD

**Issue by mzpqnxow** [OJ/gobuster#250]
Currently doing automated (or manual) post-processing on gobuster directory-mode output usually involves an approach that analyzes the status codes and size values of the responses to each of the URLs- for example, one might flag a certain size as "uninteresting" if it occurs more than `n` times, where `n` is some arbitrary threshold. This is a very rudimentary approach but works pretty well to reduce uninteresting cases

Another thing that would be very useful in my view, especially for programmatic analysis, would be to (optionally) log the content-type returned by the server for each URL that is considered a "positive" finding. This could be implemented much in the same way as how length was implemented- an optional flag that causes it to be printed to the output stream

What are your thoughts on adding this as a feature? Is there any specific reason it isn't already implemented, aside from that it was maybe considered out of scope for the role of `gobuster`?

Curious to hear your thoughts.

Thanks

**Comment by OJ** [comment]
Yup, I do like this idea :) Content type is useful for sure.
