### ISSUE TITLE
delay option

### ISSUE THREAD

**Issue by GopherZzz** [OJ/gobuster#256]
Hello, the delay (--delay) is a cool new feature, but it doesn't work properly with the extra extension (-x) param.
For example when I use '--delay 1000ms -x txt,php -t 1', my expectation is 1 request per 1 second.
But now, using v.3.1.0, I see 3 requests per second (word1, word1.txt and word1.php) and then a one-second delay before the next word2 from my wordlist.
My expectation is: word1 -- 1s delay -- word1.txt -- 1s delay-- word1.php -- 1s delay -- word2 -- 1s delay -- word2.txt -- ...
In case there is no option 'extension only', it is difficult to use this tool for enumerating when some protection like fail2ban exists.

**Comment by firefart** [comment]
this should be no problem anymore with the latest version
