### ISSUE TITLE
gobuster acting weird and logging all over the terminal

### ISSUE THREAD

**Issue by rafiibrahim8** [OJ/gobuster#258]
https://user-images.githubusercontent.com/30957188/102727236-b9e16a80-434e-11eb-87b2-bbe15b91bc67.mp4

It is hard to explain what is going on. Take a look at the video.

**OS:** elementary OS 5.1.7 Hera x86_64

**Comment by lucasmag** [comment]
Hey @rafiibrahim8 I'm facing the same issue. Did you resolve your problem?
