### ISSUE TITLE
gobuster not recognizing flags 

### ISSUE THREAD

**Issue by Shoknohota** [OJ/gobuster#268]
here's the command i typed : 
`gobuster dir -u http://10.10.196.63/ -w /usr/share/wordlists/SecLists-master/Discovery/Web-Content/directory-list-2.3-medium.txt`
the output I get : 
2020/12/30 11:05:06 [!] 2 errors occurred:
       * WordList (-w): Must be specified (use `-w -` for stdin)
       * Url/Domain (-u): Must be specified

i don't know what could be the issue here I tried reinstalling, setting up a virtual environment in python, restarting the system even reinstalling python itself 
also tried to use different versions of python but had no luck finding how 
read a blog about using gobuster -v3 syntax vs -v2 but also did not find anything 
I am running ubuntu 20 and a complete noob sorry for the hassle and thanks in advance

**Comment by FireFart** [comment]
You are using an out of date version of gobuster. To get the new version please take a look at the readme:
https://github.com/OJ/gobuster#easy-installation
