### ISSUE TITLE
The -l, (include length) flag isn't working in dir mode

### ISSUE THREAD

**Issue by johanssontobbe** [OJ/gobuster#270]
Version 3.1.0 gives the error message:
`Error: unknown shorthand flag: 'l' in -l`

**Comment by FireFart** [comment]
`-l` was replaced with `--hide-length` in 3.1

**Comment by fbi4gent** [comment]
While `gobuster help dir` shows that `-l` is the same as `--hide-length` github's README doesn't reflect that.
