### ISSUE TITLE
append-domain

### ISSUE THREAD

**Issue by A9HORA** [OJ/gobuster#273]
Hello,

I'm using the latest version of gobuster.
As per mentioned example syntax in the repository, I tried to bruteforce my test target in vhost mode. As a result, it's returning  errors as per the attached image. Please help me to understand this.
It would be a great help if you provide an example the way you did on README.md page.

![WinError](https://user-images.githubusercontent.com/13888048/104149352-e3e0f680-53fb-11eb-8066-2e5a9cde7cc0.JPG)

**Comment by FireFart** [comment]
Hi,
thanks this bug has no been fixed in master. If you update your gobuster intsall it should now work

**Comment by A9HORA** [comment]
@FireFart thank you for such quick response.
It would be a great help if you provide an usage example of the **--append-domain** flag of **gobuster vhost** mode.

**Comment by FireFart** [comment]
If you do `-u https://domain.com` append domain will generate the domains like `https://word1.domain.com` , `https://word2.domain.com` , ...
Without this flag you need to include the full domain in your wordlist on every entry
