### ISSUE TITLE
Unable to exclude on response size

### ISSUE THREAD

**Issue by ssolheim** [OJ/gobuster#277]
Running gobuster dir with the flag "-fs 9001" would previously result in responses with size 9001 being ignored. However now it results in only accepting status code 9001. I cannot find any new information about how to leave out responses of specific sizes. Has the functionality been removed or is there a new command?

**Comment by sloftis2016** [comment]
--exclude-length 4561   is the option you are looking for under the dir subcommand. There isn't a short code option for now.

cmdDir.Flags().IntSlice("exclude-length", []int{}, "exclude the following content length (completely ignores the status). Supply multiple times to exclude multiple sizes.")

It worked for me on the most recent update. Please reply back if this resolves the problem.

**Comment by FireFart** [comment]
`-fs` is the command line parameter in ffuf :) In gobuster it's `--exclude-length`
