### ISSUE TITLE
Why am I not able to ?

### ISSUE THREAD

**Issue by amit-sec** [OJ/gobuster#280]
$ gobuster dns -d realme.com -t 50 -w all.txt
2021/02/24 21:24:09 [!] 2 errors occurred:
        * WordList (-w): Must be specified (use `-w -` for stdin)
        * Url/Domain (-u): Must be specified

**Comment by OJ** [comment]
Which version are you running? It looks like it's very out of date. Please make sure you're running the latest version.

**Comment by amit-sec** [comment]
I am using latest gobuster with latest go version
Installed yesterday from go sources

**Comment by No-Cellist-7780** [comment]
try getting the latest one from the releases the master branch is way behind the development branch if im not wrong or if you are on ubuntu or kali just use `sudo apt-get install gobuster`

**Comment by ebarti** [comment]
Same issue over here, installed it with:

```shell
 go get github.com/OJ/gobuster
```

Go is at latest revision:

```shell
$> go version
go version go1.16 darwin/amd64
```

Kinda weird as it seems like it really is an old version. I checked go/pkg/mod and I see that gobuster 1.4.2 was installed for some reason:

```shell
go/pkg/mod/github.com/!o!j/$> ls
gobuster@v1.4.2			gobuster@v2.0.1+incompatible
```

**Comment by OJ** [comment]
Can you please provide your operating system versions as well?

**Comment by ebarti** [comment]
For sure!

```shell
$> uname -mrsv
Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```

**Comment by MarkoH17** [comment]
I am noticing this too after installing go 1.16 and gobuster in a Debian stable-slim docker container. For reference, the docker container was build from this [dockerfile](https://github.com/depthsecurity/armory-docker/blob/05d6b58ca425ff4b9e272500ac906bb5c7d32245/Dockerfile).

Installing Gobuster
```
root@502f2445b101:~# go clean --modcache
root@502f2445b101:~# go get -u github.com/OJ/gobuster
go: downloading github.com/OJ/gobuster v1.4.2
go: downloading github.com/OJ/gobuster v2.0.1+incompatible
go: downloading golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83
go: downloading github.com/google/uuid v1.2.0
go: downloading github.com/hashicorp/go-multierror v1.1.0
go: downloading golang.org/x/term v0.0.0-20201117132131-f5c789dd3221
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading golang.org/x/term v0.0.0-20210220032956-6a3ed077a48d
go: downloading golang.org/x/sys v0.0.0-20191026070338-33540a1f6037
go: downloading github.com/hashicorp/errwrap v1.1.0
go: downloading golang.org/x/sys v0.0.0-20210301091718-77cc2087c03b
```

OS and kernel information
```
root@502f2445b101:~/go/pkg/mod/github.com# uname -a
Linux 502f2445b101 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 GNU/Linux

root@502f2445b101:~/go/pkg/mod/github.com# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

Go version
```
root@502f2445b101:~/go/pkg/mod/github.com# go version
go version go1.16 linux/amd64
```

**Comment by FireFart** [comment]
Looks like this is caused by gomodules:
`go get -u github.com/OJ/gobuster/v3` should get the v3 version, without the `v3` go get fetches the older versions it seems (this is less than intuitive)

**Comment by ebarti** [comment]
I can confirm that works
