### ISSUE TITLE
can I gobuster dir Client Side rendered websites?

### ISSUE THREAD

**Issue by dyegoaurelio** [OJ/gobuster#281]
If a website returns 200 from every path, (or 304 if its cached) like react apps with react router standard  configuration, [like this one](https://codesandbox.io/s/m4n21l3m38) can I brute force it URIs with gobuster?

I guess the only way would be to add a feature to evaluate javascript from 200 responses if needed, or am I missing something?

**Comment by FireFart** [comment]
you can only filter on the returned size but there is no way to interpret the returned javascript. But you can enumerate custom routes on this app.

**Comment by dyegoaurelio** [comment]
thanks
