### ISSUE TITLE
libgobuster io/utils

### ISSUE THREAD

**Issue by tanetane2** [OJ/gobuster#283]
Should in http.go script be imported io/ioutils instead of io?

Getting following error when building docker image:

`src/github.com/OJ/gobuster/libgobuster/http.go:114:15: undefined: io.ReadAll`
`src/github.com/OJ/gobuster/libgobuster/http.go:122:25: undefined: io.Discard`

**Comment by FireFart** [comment]
The master branch is the current development version and requires at least go1.16 as stated in the readme. If you want to build the master branch please update your golang version
