### ISSUE TITLE
Can't filter on status codes

### ISSUE THREAD

**Issue by 0bs3ssion** [OJ/gobuster#289]
Previously I was always able to filter on status code using -s. However if I do so now I get the following error:
`Error: error on parsing arguments: status-codes and status-codes-blacklist are both set, pleaes set only one`

Command I used:
`gobuster dir -u http://127.0.0.1/ -w /usr/share/seclists/Discovery/Web-Content/big.txt -s "200"`

**Comment by kastahl** [comment]
Which version are you using?

**Comment by keepit-breezy** [comment]
I'm not receiving the error code but I can't seem to get v3.1.0 to recognize the **-s** flag. I tested using the precompiled binaries after I noticed the problem using an apt-get install. Using the following command:
`./gobuster dir -s '200' -w /usr/share/wordlists/SecLists/Discovery/Web-Content/CGIs.txt -u http://127.0.0.1`

v3.1.0 output
```
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     http://127.0.0.1
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                /usr/share/wordlists/SecLists/Discovery/Web-Content/CGIs.txt
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.1.0
[+] Timeout:                 10s
===============================================================
2021/07/29 09:57:06 Starting gobuster in directory enumeration mode
===============================================================

/./                   (Status: 302) [Size: 0] [--> site/index.php/]
/index.php?chemin=..%2F..%2F..%2F..%2F..%2F..%2F..%2F%2Fetc (Status: 302) [Size: 0] [--> site/index.php/]
/index.php/123        (Status: 302) [Size: 0] [--> site/index.php/]
[ERROR] 2021/07/29 09:57:06 [!] parse "http://127.0.0.1/%NETHOOD%/": invalid URL escape "%NE"
/?mod=node&nid=some_thing&op=view (Status: 302) [Size: 0] [--> site/index.php/]
/?mod=some_thing&op=browse (Status: 302) [Size: 0] [--> site/index.php/]
/index.php?file=index.php (Status: 302) [Size: 0] [--> site/index.php/]
//                    (Status: 302) [Size: 0] [--> site/index.php/]
/?Open                (Status: 302) [Size: 0] [--> site/index.php/]
/?OpenServer          (Status: 302) [Size: 0] [--> site/index.php/]
[ERROR] 2021/07/29 09:57:06 [!] parse "http://127.0.0.1/%a%s%p%d": invalid URL escape "%a%"
/%2e/                 (Status: 302) [Size: 0] [--> site/index.php/]
[ERROR] 2021/07/29 09:57:06 [!] parse "http://127.0.0.1/default.htm%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%": invalid URL escape "%"
/../../../../../../../../../boot.ini (Status: 400) [Size: 301]
/../../../../winnt/repair/sam._ (Status: 400) [Size: 301]
////./../.../boot.ini (Status: 400) [Size: 301]
.....more output.....
```

v3.0.1 Output
```
===============================================================
Gobuster v3.0.1
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@_FireFart_)
===============================================================
[+] Url:            http://127.0.0.1
[+] Threads:        10
[+] Wordlist:       /usr/share/wordlists/SecLists/Discovery/Web-Content/CGIs.txt
[+] Status codes:   200
[+] User Agent:     gobuster/3.0.1
[+] Timeout:        10s
===============================================================
2021/07/29 09:58:19 Starting gobuster
===============================================================
[ERROR] 2021/07/29 09:58:19 [!] parse http://127.0.0.1/%NETHOOD%/: invalid URL escape "%NE"
[ERROR] 2021/07/29 09:58:20 [!] parse http://127.0.0.1/%a%s%p%d: invalid URL escape "%a%"
[ERROR] 2021/07/29 09:58:20 [!] parse http://127.0.0.1/default.htm%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%: invalid URL escape "%"
/phpmyadmin/ (Status: 200)
/cgi-bin/admin.cgi?list=../../../../../../../../../../etc/passwd (Status: 200)
/cgi-bin/admin.cgi (Status: 200)
/cgi-bin/test.cgi (Status: 200)
===============================================================
2021/07/29 09:58:27 Finished
===============================================================
```
I also notice that in the 3.0.1 output there is a **Status codes: 200** whereas in the 3.1.0 output this is missing and instead replaced with the default **Negative Status Codes: 404**

**Comment by n3rada** [comment]
Currently on `Gobuster v3.1.0` with Arch Linux kernel `x86_64 Linux 5.15.13-arch1-1` and it's not working either.

I wanted to launch `gobuster dir -u http://challenge01.root-me.org/realiste/ch3/ -w ~/wordlists/seclists/Discovery/Web-Content/common.txt -s 200,401` and I got the mentionned error `Error: error on parsing arguments: status-codes and status-codes-blacklist are both set, please set only one`

**Comment by n3rada** [comment]
Currently on `Gobuster v3.1.0` with Arch Linux kernel `x86_64 Linux 5.15.13-arch1-1` and it's not working either.

I wanted to launch `gobuster dir -u http://<ip> -w ~/wordlists/seclists/Discovery/Web-Content/common.txt -s 200,401` and I got the mentionned error `Error: error on parsing arguments: status-codes and status-codes-blacklist are both set, please set only one`

**Comment by firefart** [comment]
you can append `-b ""` to unset the negative status codes. We switched from a whitelist to a blacklist so in the default configuration only 404 is ommitted from the outputs. I would suggest to also use `-b` instead of `-s` as you might miss some status codes with `-s` (like 405)

**Comment by MacTavish-exe** [comment]
How many status codes am i going to exclude??? Are you joking with me???

**Comment by HuliKos** [comment]
What is the new -b/-s to exclude the status code on vhost mode under version 3.6?
![image](https://github.com/OJ/gobuster/assets/90301703/759f7cb4-8608-48f7-83eb-da7c421e0ef5)

**Comment by firefart** [comment]
> What is the new -b/-s to exclude the status code on vhost mode under version 3.6? ![image](https://user-images.githubusercontent.com/90301703/265216789-759f7cb4-8608-48f7-83eb-da7c421e0ef5.png)

there is no such option. VHOST mode operates differently. If a vhost with a different content is detected it will be reported. You can only use `exclude-length` to exclude those  which you are not interested in
