### ISSUE TITLE
Feature request: PKCS 12 certificate authentication

### ISSUE THREAD

**Issue by Paradoxis** [OJ/gobuster#290]
Hi! 

I love the tool but I was wondering if brute-forcing directories could support [PKCS 12 / PFX certificate authentication](https://en.wikipedia.org/wiki/PKCS_12)? I've run into the issue a couple of times where an application expects a certificate instead of basic auth and I'm unable to efficiently scan the application for files.

Current workaround is to install the certificate in Burp and proxy all requests through it however that ends up with a huge performance hit, as well as cluttering my burp file.

**Comment by firefart** [comment]
this is implemented in the dev branch and will be released with version 3.3
