### ISSUE TITLE
Question: why doesn't gobuster ship with wordlists like dirb?

### ISSUE THREAD

**Issue by gmelodie** [OJ/gobuster#291]
It might be a rookie mistake, but I always find myself downloading `dirb` just for their wordlists and then linking them to `gobuster`. Maybe we could ship gobuster with the dirb wordlists?

**Comment by firefart** [comment]
the wordlists are included by the distro maintainers. If you want wordlist with gobuster in kali you can open a request on https://bugs.kali.org/
