### ISSUE TITLE
Error in syntax?

### ISSUE THREAD

**Issue by NoNameoN-A** [OJ/gobuster#292]
Hi i'm trying to use your tool but i don't understand what is the problem.
I send it
` gobuster dir -u https://10.10.175.13/ -w ~/wordlists/shortlist.txt`

and I have this error
`2021/04/21 15:27:00 [!] 2 errors occurred:
        * WordList (-w): Must be specified (use '-w -' for stdin)
        * Url/Domain (-u): Must be specified`

But if i try just this below works
` gobuster -u https://10.10.175.13/ -w ~/wordlists/shortlist.txt`

**Comment by FireFart** [comment]
you are using an old version of gobuster. Be sure to update to the latest version to use the new `gobuster dir` syntax

**Comment by matrixbot123** [comment]
what is the correct syntax then
