### ISSUE TITLE
Feature Request: Output flag to have a default

### ISSUE THREAD

**Issue by IppSec** [OJ/gobuster#293]
I would love if I could specify -o with no options and have it default to $domain-$args.gobuster.... I can't count the number of times I've just changed the output filename but forgot to change the URL. 🤦‍♂️

**Comment by synap5e** [comment]
Maybe also allow a directory and have it use the automatic default filename too. e.g. `-o outfiles/gobuster/`

**Comment by firefart** [comment]
you can easily do that outside of gobuster by using variabkles and the `-o` switch

**Comment by secxue** [comment]
> `-o`您可以使用变量和开关轻松地在 gobuster 之外执行此操作

Hi bro, can you give me an example?
