### ISSUE TITLE
Gobuster keeps closing my shell

### ISSUE THREAD

**Issue by Waxxx333** [OJ/gobuster#295]
I've used Gobuster on Arch before and never had an issue. I just installed Arch on a new MSI last week and when I run gobuster, my shell freezes for a moment and then just force-closes my shell. I tried to remove it and reinstall it ( from the BlackArch repo ). Any help would be appreciated.

**Comment by FireFart** [comment]
Hi,
the version from the BlackArch repo is not maintained by us so I would suggest asking for help on the BlackArch forums/irc
