### ISSUE TITLE
Error  : parse

### ISSUE THREAD

**Issue by jrod1776** [OJ/gobuster#296]
Hello
![image](https://user-images.githubusercontent.com/77260537/119275700-87c98280-bbe4-11eb-919f-56c86de62e88.png)
#
The best way to describe my issue is in the attached photo. I ran the tool and received what appeared to be three paths. I am not understanding if these directories found are found but it is suggesting errors posed in the characters. If possible could you giver me a basic understanding of what these errors are about?

**Comment by FireFart** [comment]
It looks like your wordlist contains entries which produce invalid urls (like the `[%s]`). Every entry from the wordlist is appended to the domain so if this combination produces an invalid url golang will complain about it
