### ISSUE TITLE
error on running gobuster: 301 response missing Location header

### ISSUE THREAD

**Issue by christophetd** [OJ/gobuster#300]
When testing an application that responds with 301 status codes without a Location header, gobuster is unable to run.

Expected behavior: Optionally or by default consider a 301 as a redirect, even if it doesn't have a location header

Thoughts?
Thanks!

**Comment by FireFart** [comment]
hi @christophetd ,
can you please share the exact error message? I assume this error comes from the golang source itself as a 301 without a `Location` header is an invalid response.

**Comment by wwallace** [comment]
Error: error on running gobuster: Get "https://.../...": 301 response missing Location header

**Comment by firefart** [comment]
https://tip.golang.org/doc/go1.19

> The HTTP client will handle a 3xx response without a Location header by returning it to the caller, rather than treating it as an error.

this will finally be fixed with go1.19 (not yet released)

**Comment by firefart** [comment]
go 1.19 is now released so this bug should be fixed
