### ISSUE TITLE
There's an error everytime i use gobuster

### ISSUE THREAD

**Issue by jhlol** [OJ/gobuster#301]
Every time i try to do gobuster dir -u https://169.254.169.254 -w /home/jadhilal2008/wordlists/wordlist.txt it says that the word list and url must be specified but im 100% im doing it correctly what could be the issue?

**Comment by OJ** [comment]
Which version are you using?

**Comment by FireFart** [comment]
most probably an old version using the new syntax or vice versa. Closing due to lack of response
