### ISSUE TITLE
note: module requires Go 1.16

### ISSUE THREAD

**Issue by mydevice** [OJ/gobuster#302]
How to fix this error ? 

# github.com/OJ/gobuster/v3/libgobuster
libgobuster/http.go:114:15: undefined: io.ReadAll
libgobuster/http.go:122:25: undefined: io.Discard
note: module requires Go 1.16

**Comment by FireFart** [comment]
Hi,
you need to install the latest version of golang or at least 1.16 to build the master branch:

https://golang.org/doc/install
