### ISSUE TITLE
the server returns a status code that matches the provided options for non existing urls

### ISSUE THREAD

**Issue by Benson306** [OJ/gobuster#306]
Error: the server returns a status code that matches the provided options for non existing urls. http://example.com/72e58910-2bfb-443e-824e-9bd8bcc484de => 403 (Length: 118). To continue please exclude the status code, the length or use the --wildcard switch
the command used is: gobuster dir -u example.com -w /usr/share/wordlists/dirb/common.txt

**Comment by FireFart** [comment]
you need to do exactly what the error message tells you. I case you need more information, consult `--help`

**Comment by Alibakhshov** [comment]
Try to use the command  **--wildcard switch**  at the end:
