### ISSUE TITLE
Error on 'Keep-Alive: timeout' 

### ISSUE THREAD

**Issue by RaduNico** [OJ/gobuster#307]
I've encountered a website which employs an interesting protection mechanism. Attempting to brute force the root directory results in a 301 response with no content. However it has two headers set `Connection: Keep-Alive` and `Keep-Alive: timeout=20`. This results in gobuster giving a timeout error:

```
$ gobuster dir -w wordlist.txt -u https://censored.org/ 
===============================================================
Gobuster v3.1.0
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     https://censored.org/
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                wordlist.txt
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.1.0
[+] Timeout:                 10s
===============================================================
2021/08/31 14:55:16 Starting gobuster in directory enumeration mode
===============================================================
Error: error on running gobuster: unable to connect to https://censored.org/: net/http: request canceled (Client.Timeout exceeded while reading body)
```

I've tried using a higher timeout (about 22 seconds) but this results in gobuster taking very long to finish the brute force. Is there a way to tell gobuster to ignore the Keep-Alive header, if all the expected content has been received? The browser completely ignore this timeout because it redirects immediately. In this particular case no content is sent back. For reference this is the received response (no content response):

```
$ curl -I https://censored.org/
HTTP/1.1 301 Moved Permanently
Date: Tue, 31 Aug 2021 11:53:55 GMT
Location: https://censored.org/censored/login.html
Keep-Alive: timeout=20
Connection: Keep-Alive
```

I can provide any additional information regarding this issue.

**Comment by firefart** [comment]
the keep-alive headers only indicate how long an idle connection can be reused and do not interfer with the current request. This looks like an overloaded server or a user agent block instead
