### ISSUE TITLE
update release

### ISSUE THREAD

**Issue by TheBotlyNoob** [OJ/gobuster#308]
Update the release because the current one is broken

**Comment by FireFart** [comment]
what do you mean by broken?

**Comment by l0bc** [comment]
the `v3` folder was removed from master and  almost all `*.go` files are pointing to the old path.
e.g.
main.go --> `import 'github.com/OJ/gobuster/cli/V3/cmd'` 
when it should be: `import 'github.com/OJ/gobuster/cli/cmd'`

**Comment by FireFart** [comment]
Please see the readme on how to install gobuster. Everything is working as expected
