### ISSUE TITLE
gobuster command not working on ubuntu

### ISSUE THREAD

**Issue by hadamssmith** [OJ/gobuster#310]
gobuster dir -u http://http://10.10.68.57:3333 -w /usr/share/wordlists/disbuster/directory-list-2.3-medium.txt
2021/10/13 20:53:46 [!] 2 errors occurred:
	* WordList (-w): Must be specified (use `-w -` for stdin)
	* Url/Domain (-u): Must be specified
	
Even while I try the gobuster command I still get that error
 gobuster
2021/10/13 20:58:14 [!] 2 errors occurred:
	* WordList (-w): Must be specified (use `-w -` for stdin)
	* Url/Domain (-u): Must be specified

**Comment by dithermedaddy** [comment]
I'm having the exact same issue, and gobuster is updated. Anyone else have this issue?

**Comment by dithermedaddy** [comment]
Hey, yeah sorry man I am obvs a noob, I installed it first on Ubuntu thinking that if I used apt install it has to be the latest version. So I'm glad I struggled a bit and finally took the time to read the github page and learned something through the process - I now know what a binary is ;-p Thanks for creating such a killer tool, keep well.

**Comment by symya** [comment]
> Hey, yeah sorry man I am obvs a noob, I installed it first on Ubuntu thinking that if I used apt install it has to be the latest version. So I'm glad I struggled a bit and finally took the time to read the github page and learned something through the process - I now know what a binary is ;-p Thanks for creating such a killer tool, keep well.

Did you solve this error? Please tell me how to do that ,thanks
