### ISSUE TITLE
Failed to parse Location header

### ISSUE THREAD

**Issue by gimmeAPIkeyplz** [OJ/gobuster#313]
Gobuster was working fine for me all day but now it's throwing an error message. Tried uninstalling and reinstalling but that didn't work. Tried removing some flags and changing the wordlist. Any suggestions? The IP im running it against is up.

gobuster dir --url http://x.x.x.x -w /usr/share/wordlists/dirbuster/directory-list-1.0.txt -q --wildcard -z -r -k

Error: error on running gobuster: unable to connect to http://x.x.x.x/: Get "http://x.x.x.x/": failed to parse Location header "https://\\x.x.x.x\\/": parse "https://\\x.x.x.x\\/": invalid character "\\" in host name

**Comment by firefart** [comment]
this is an error returned by golangs http library as the server sends an invalid response back but enumeration should continue
