### ISSUE TITLE
Feature Request.Print Final Url too

### ISSUE THREAD

**Issue by ericnyamubbp** [OJ/gobuster#314]
Hi

It would be very beneficial if gobuster would print he final url  alongside the directory checked.This will be nice because sometimes when you access a particular directory you might be redirected to another login page which might be vulnerable and cannot be found by traditional means.So the desired output of this feature will be like shown below 

![Screenshot from 2021-11-07 15-36-39](https://user-images.githubusercontent.com/74705471/140645220-6ea5fc3f-a188-4278-9d73-fe1e247bb675.png)

I hope you implement it.

Thanks

**Comment by firefart** [comment]
redirects are now printed with the resulting url
