### ISSUE TITLE
how to finish gobuster when error line (context deadline exceeded (Client.Timeout exceeded while awaiting headers))

### ISSUE THREAD

**Issue by mominul0x01** [OJ/gobuster#320]

**Comment by firefart** [comment]
This means the server timed out. There is a rery option on the `dev` branch but not yet ready to mege into master. You can try to reduce threads or increase timeouts

**Comment by dageita** [comment]
which parameter is used to increase timeout in handler or server?

**Comment by rohank92** [comment]
> which parameter is used to increase timeout in handler or server?

--timeout
