### ISSUE TITLE
Not sure why it wont accept my wordlist or domain. 

### ISSUE THREAD

**Issue by Gandalf138** [OJ/gobuster#327]
Ive updated gobuster and go. 

gandalf@GLaDOS:~/gobuster$ sudo gobuster dir -w /usr/share/wordlists/common.txt -u "10.129.16.169"'
2022/03/19 14:50:19 [!] 2 errors occurred:
        * WordList (-w): Must be specified (use `-w -` for stdin)
        * Url/Domain (-u): Must be specified

gandalf@GLaDOS:~ /gobuster$ go version
go version go1.17.7 linux/amd64
gandalf@GLaDOS:~ /gobuster$ gobuster version
3.1.0

**Comment by Gandalf138** [comment]
I've seen things about using proper syntax but everywhere I've looks has it written like this.

**Comment by FireFart** [comment]
looks like your sudo call executes an older version of gobuster, you need to install the latest one to use the new syntax

**Comment by Gandalf138** [comment]
how would i go about doing that if i already have the latest version?
