### ISSUE TITLE
Wordlist Support WildCard/RegEx or Directory Input

### ISSUE THREAD

**Issue by aress31** [OJ/gobuster#328]
A little suggestion, when running content discovery, or any type fuzzing, I like to organise my wordlists logically with different naming conventions / within different directory.

Therefore, I would love to see an option (or just refactoring the `-w switch`) to specify a directory. All the files within this specified directory should be sequentially parsed and used as wordlists, rather than the current behaviour of having to re-run the program `X times` with each different wordlists within this directory, therefore creating many different `outputs` that should then be post-processed.

Also, I have wordlists with specific naming conventions, so supporting `regex` - or at least `wildcard` - would help, a use case could be for example `-w wordpress-*.lst`.

Looking forward to hearing your thoughts on the idea.

**Comment by firefart** [comment]
please just use a bash loop to loop over the files or cat them and pipe them into gobuster and use stdin as a wordlist
