### ISSUE TITLE
Request for Recursive search feature 

### ISSUE THREAD

**Issue by hamzanadeem44** [OJ/gobuster#332]
Hi gobuster Team,

I really love and use this tool while performing security assessments. One thing that I found missing in it, there is no way to recursively search for directories/URLs while using ``dir`` section.

It would be awesome if you can introduce the feature of recursive search.

**Expected Results:**
```
gobuster dir -R -u https://target.com/ -w wordlist_here -e -x php,html,sql,save,txt
```
**-R:** for recursively scan for files/directories

**Comment by firefart** [comment]
hi, this is currently not possible without big rewrites of the code base but we are happy to accept prs
