### ISSUE TITLE
gobuster length filter

### ISSUE THREAD

**Issue by Vulpure** [OJ/gobuster#335]
I am using gobuster and here is a question I did not found the answer.
It is how to filter the length of response.

This is the Error:
Error: the server returns a status code that matches the provided options for non existing urls. xxx => 200 (Length: 725). To continue please exclude the status code, the length or use the --wildcard switch

I need to find a dir which http status is 200 and length is not 725 . It seems that gobuster only support to filter the http status .Pls tell me it that how can I type the command if gobuster support length filter.
Thank you very much .

**Comment by firefart** [comment]
`-s 200 -b "" --exclude-length 725` on the `dev` branch
