### ISSUE TITLE
Headers option changing case

### ISSUE THREAD

**Issue by Freccia** [OJ/gobuster#337]
While using option `--headers` I noticed it changed the case of the header's name.

Example request :
![image](https://user-images.githubusercontent.com/15819880/169069597-18ebe10b-748f-4f47-9956-c0c60774fdad.png)

Result : 
![image](https://user-images.githubusercontent.com/15819880/169069884-2505a41e-ffad-4d34-9da1-8b9fd1960f77.png)

Now, the API I am using doesn't like it, since it's case sensitive, so I really need it to use the case I am giving.

**Comment by Freccia** [comment]
I found the issue. Proposing pull-request #338 to fix it.

Apparently [http.Header](http://godoc.org/net/http#Header) [Add](http://godoc.org/net/http#Header.Add) and [Set](http://godoc.org/net/http#Header.Set) methods canonicalize the header name when adding values to the header map.

There is a trick to fix this, as stated [here](https://stackoverflow.com/questions/26351716/how-to-keep-key-case-sensitive-in-request-header-using-golang)

**Comment by firefart** [comment]
thanks this is now implemented on the dev branch
