### ISSUE TITLE
is that possible to skip line on matching ?

### ISSUE THREAD

**Issue by kolet** [OJ/gobuster#340]
hi ,

i have 2 sets of payload .
first payload is a wordlist .
second payload numbers . 0000-9999 (bf)

i'd like for the scan to stop the BF on  a line when matching a redirect(status code 302)  or length (greater then normal)
so instead of continue going through 10k for each line in payload 1 (wordlist) 
it will stop and continue with the other lines . 
how can i accomplish that ? 

thanks !

**Comment by firefart** [comment]
just use the parameters to only match on 30x and press ctrl+c on a hit. there is no such thing implemented
