### ISSUE TITLE
Return final page URL from d.http.Request in gobusterdir

### ISSUE THREAD

**Issue by drwtsn95** [OJ/gobuster#342]
It will be easier to import code from `libgobuster` without copying it if you add one more return value to `func (client *HTTPClient) Request` method in `libgobuster/http`. You can use `resp.Request.URL.String()` as such value.
P.S. i am writing additional functionality for `gobusterdir`, so i copied it's code, but `libgobuster` code is intended to be only imported from github.

**Comment by firefart** [comment]
whats the purpose of this? You already pass in the url to `Request` so why return it again?

**Comment by drwtsn95** [comment]
Nice to see an answer here! So, there is some sense there. You are right about url, but if one was redirected after fetching some url, one wants to have a final redirect url to fill some cache map of final redirect urls. It is needed for PreRun phase when one wants to collect some bodies and urls of 404 or error like responses.

**Comment by firefart** [comment]
currently all response headers are returned so you can easily extract the redirect urls (dir mode also does that to print out redirects)

**Comment by drwtsn95** [comment]
I am talking not about single redirect, but redirect chain with length > 1.
