### ISSUE TITLE
Support for HTTP Digest & NTLM Authentication

### ISSUE THREAD

**Issue by M-Davies** [OJ/gobuster#348]
Although the Basic Auth support (https://github.com/OJ/gobuster/pull/15) is useful, I have tested a lot of applications that require other forms of HTTP Authentication (such HTTP [Digest](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Digest) and [NTLM](https://curl.se/rfc/ntlm.html)) and would love to be able to run GoBuster against them.

Would it be possible for this support to be introduced that's a similar manner to the current Basic auth method?

**Comment by firefart** [comment]
haven’t found an ntlm library so far for golang that’s useable so I guess it’s currently not possible. But you can proxy gobuster through burp and let burp handle the authentication as a workaround
