### ISSUE TITLE
Gobuster seems to stop after ~1100 requests?

### ISSUE THREAD

**Issue by Viss** [OJ/gobuster#35]
![image](https://cloud.githubusercontent.com/assets/1756255/19498046/fde1a8b6-9543-11e6-91b4-40028af6736f.png)

Originally I tried pushing it through tor, it stopped with no error message after ~1200 requests.
I tried against my own server not over tor, and it stopped at ~1100.

The wordlist I'm using had ~382,000 items in it, so I'm not sure what's going on..
is there a preferred troubleshooting step you'd like me to follow here?

**Comment by Viss** [comment]
fyi, these cmdlines end with  | wc -l 
and contain -v
the idea was that I wanted to see how many requests they made before the binary quit working

**Comment by OJ** [comment]
Thanks @viss. I've had a bit of a play with this and I'm seeing inconsistent results. Let me do some more testing and I'll get back to you.

**Comment by Viss** [comment]
no worries!
Let me know if there's stuff you want me to try on this side, or if you
want a copy of that dictionary!

**Comment by OJ** [comment]
Nah the dictionaries I have are more than big enough. The one I usually use is 1.5M lines.

I'm seeing different behaviours on local webservers vs remote webservers. Could be that certain attempts are erroring out without being caught.

**Comment by eur0pa** [comment]
I'd like to chime in on this issue—it seems to be happening to me as well. gobuster will randomly stop doing its thing and either hang, or return an evidently cut-down list of results. To be honest, I spent some time trying to track down the issue but I can't seem to pin it anywhere

**Comment by FireFart** [comment]
This can also be caused because go hast an infinite timeout on requests. If the website sends you to a tarpit, you will wait forever. I implemented a timeout parameter here if you wanna try:
https://github.com/OJ/gobuster/pull/79

**Comment by OJ** [comment]
I've never been able to repro this, but I think this is now sorted in 2.0.0. Thanks!
