### ISSUE TITLE
Handling of the CTRL+C signal is not consistent across platforms

### ISSUE THREAD

**Issue by OJ** [OJ/gobuster#36]
I'm seeing this behave strangely in different contexts, and so I might just remove it until I figure out what is going on. OSX seems to be the strangest.

**Comment by rverton** [comment]
What strange behaviour did you observe? I have no problems with CTRL+C under OSX. I read that sometimes there are problems with catching signals when running via `go run`, but I have no problems doing it this way, too.

[The docs](https://golang.org/pkg/os/#Signal) also say os.Interrupt is available on all systems.

**Comment by OJ** [comment]
Should be good now.
