### ISSUE TITLE
Cannot cancel when using 1 thread

### ISSUE THREAD

**Issue by theawkwardchild** [OJ/gobuster#360]
Only effects when using 1 thread (-t 1). When you try to cancel it running, it will respond with "[!] Keyboard interrupt detected, terminating", but then hangs there. I assume it's one thread got caught up doing something else and can't close itself. 

To reproduce: run a dir scan against a website using the -t 1 flag, once it has started try canceling the program with CTRL + C. 

Workaround: run it with more than 1 thread.

**Comment by firefart** [comment]
Hi,
which version of buster are you running? I tried it with the current version and can not reproduce it locally
