### ISSUE TITLE
Progress goes over 100%

### ISSUE THREAD

**Issue by Existential-Kernel** [OJ/gobuster#365]
![image](https://user-images.githubusercontent.com/77142078/200094650-ccb683b2-cd2e-4769-8133-df91b9d97cce.png)
I'm not sure if some sort of floating point accuracy issue is the reason for this but yeah, the image is self-explanatory (I'm using version 3.1.0 with the `dir` option)

edit: it's at 183% now wtf

**Comment by firefart** [comment]
do you have retries enabled?

**Comment by Existential-Kernel** [comment]
> do you have retries enabled?

Idk how to enable that feature, I have no idea that was even a thing to begin with. All I did was 
`gobuster dir --url <url> -w <wordlist>`

**Comment by firefart** [comment]
Which version of gobuster are you running?

**Comment by Existential-Kernel** [comment]
> Which version of gobuster are you running?

3.1.0

**Comment by firefart** [comment]
can you please try again with the latest version to see if the bug is still there?

**Comment by Existential-Kernel** [comment]
Sorry but I'm not gonna bother with this anymore, I'm not going to wait 4+ hours for a single bug test again
