### ISSUE TITLE
gobuster not usable against TLS 1.0

### ISSUE THREAD

**Issue by rxt30** [OJ/gobuster#367]
If using `gobuster` version `3.2` and higher, `gobuster` quits with the following error if used against a target with `TLS 1.0`, even if using `-k`:
```
Error: error on running gobuster: unable to connect to https://<target.ip>/: Get "https://<target.ip>/": tls: server selected unsupported protocol version 301
```

This error seems to more likely be related to the migration to `Go 1.19`, then by a change in the source code of `gobuster`.

Should `gobuster` be usable against targets with `TLS 1.0` or is it now out of scope of `gobuster`?

**Comment by firefart** [comment]
Thanks for the hint I enabled TLS1.0 and TLS1.1 on the dev branch here https://github.com/OJ/gobuster/commit/c3897042188cbbdb45d29adce57a1965dd9e6947

You can try it with `go install github.com/OJ/gobuster/v3@dev` until a new version is released
