### ISSUE TITLE
Canary to filter DNS Addresses 

### ISSUE THREAD

**Issue by n0x00** [OJ/gobuster#38]
Don't kill me...

would there be any value in adding a canary?
random string or user supplied...

If the target resolves every name provided in the list those that have the same IP as the canary domain automatically get stripped out , suppressed,hidden whatnot

**Comment by OJ** [comment]
We already have that feature built in, but it does it by itself rather than having a user-supplied value. See here: https://github.com/OJ/gobuster/blob/master/main.go#L488

Is that what you mean?

**Comment by n0x00** [comment]
yeah but I've have had cases where with the -fw switch set it continues to resolve all names in the list and I have to sort by removing all IP Addresses with the non-existent subs 

can show you, but not on here if that's okay ?

using:  ``` gobuster -m dos -u domain.com -t 20 -w /path/to/list.lst -I -fw ```

**Comment by OJ** [comment]
Sure, hit me on Skype.

**Comment by OJ** [comment]
hey @n0x00 can you let me know the deets of this so we can move ahead with it mate? Thanks!

**Comment by n0x00** [comment]
dude, dont laugh... i'm totally locked out of my github :D

phone broke, 2fa ... no back up codezzzz

**Comment by n0x00** [comment]
I will hit you up on skype soon tho ! and ... find a domain we can example
