### ISSUE TITLE
Gobuster v3.0.1 enumerates vhosts but 3.4 does not?

### ISSUE THREAD

**Issue by bc1121** [OJ/gobuster#382]
I stumbled across this example today. I was trying to figure out why one machine could enumerate the vhosts in https://tryhackme.com/room/webenumerationv2#task-6 but another could not.

It turns out that the machine that was successful was running Gobuster 3.0.1, and the computer that was not successful was running the latest version 3.4.

I removed gobuster and downloaded the 3.0.1 binary. Ran the test (right terminal) that you see below. Then apt installed the latest gobuster and ran the 2nd test (left terminal) which yielded the "correct" results according to the lab.

This may be related to the networking of the lab environment but I thought you may want to examine the results since, to the layman (myself in this case), the results of the the older version appear more correct than the results of the new version.

Could this be related to https://github.com/OJ/gobuster/issues/317?

gobuster vhost -u http://webenum.thm -w /usr/share/seclists/Discovery/DNS/subdomains-top1million-5000.txt -t64

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/5932828/210873213-6fc25650-f9b1-49dd-af71-5a7afb688011.png">

**Comment by bc1121** [comment]
Further testing reveals gobuster v3.1 enumerates the so called "correct" vhosts but v3.2 does not.

**Comment by firefart** [comment]
It looks like you are missing the —append-domain flag but it depends on your wordlist. Try —help for all options or verbose mode to see checked vhosts

**Comment by bc1121** [comment]
Adding the --append-domain flag did the trick.

I experimented with that flag while I tried different wordlists but I once I got it to work on a different machine without the flag, I disregarded the flag altogether and assumed that I had problems with my networking or proxy before I discovered that I was using different versions of gobuster. Thanks for the help. Thanks for your product.

**Comment by paul0ss** [comment]
![image](https://github.com/OJ/gobuster/assets/60821308/7f778ab3-ed5e-4e49-9974-0bf21aa11981)

Unfortunately, the issue still didnt get fixed:(
The --append-domain does not solve it.
