### ISSUE TITLE
Error: unknown flag: --wildcard

### ISSUE THREAD

**Issue by alsigit** [OJ/gobuster#387]
Hi all,
Why I can't use wildcard flag ?
Any suggestions?
Here is my error

===============================================================
Gobuster v3.4
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Url:                     http://127.0.0.1:8888
[+] Method:                  GET
[+] Threads:                 10
[+] Wordlist:                /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt
[+] Negative Status codes:   404
[+] User Agent:              gobuster/3.4
[+] Timeout:                 10s
===============================================================
2023/01/22 12:18:05 Starting gobuster in directory enumeration mode
===============================================================

Error: the server returns a status code that matches the provided options for non existing urls. http://127.0.0.1:8888/1ff69df8-2f39-4eb3-a762-f399d0bd7837 => 200 (Length: 2835). To continue please exclude the status code or the length
                                                                                                                   
┌──(abc㉿kali)-[~/lab/crapi]
└─$ gobuster dir -u http://127.0.0.1:8888 -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt --wildcard
Error: unknown flag: --wildcard

Thank you

**Comment by firefart** [comment]
Because there is no wildcard flag. The error message lists all options. Use —help to see them all
