### ISSUE TITLE
Status Code "301" on searching with gobuster

### ISSUE THREAD

**Issue by DxcR3T** [OJ/gobuster#390]
when using the gobuster it seems show an error.

i'm using the payload below:
./gobuster dir -u https://.. -w ~/node-dirbuster/lists/directory-list-2.3-medium.txt -b "" -k 

And the result showing below:
the server returns a status code that matches the provided options for non existing urls. https://../3f75e0e5-dd76-4caf-a937-ed7c56a994bc => 301 (Length: 0). To continue please exclude the status code or the length

im using gobuster v3.4 and golang go1.19.5 (as i assume from previous error came from golang)
if i use the payload  ( -b "301,404" ) it works fine, but i can't see the 301 on the result.

any way to prevent the error?
Thanks

**Comment by firefart** [comment]
This is no error, it just tells you to configure your gobuster correctly to work with this site. If all urls return a 301 there is no sense in treating those as positive status codes
