### ISSUE TITLE
2 errors occurred WordList [(-w): Must be specified (use `-w -` for stdin); Url/Domain (-u): Must be specified]

### ISSUE THREAD

**Issue by gbiagomba** [OJ/gobuster#391]
I am having issues running the tool, I keep getting the below error when I run the following: `gobuster dns -u "example.com" -i -t 25 --wordlist "/path/to/subdomains.list" -o "gobuster_dns_output.txt"`

```
2023/02/08 15:42:43 [!] 2 errors occurred:
        * WordList (-w): Must be specified (use `-w -` for stdin)
        * Url/Domain (-u): Must be specified
```

**Comment by firefart** [comment]
you are executing an older version. check your paths and installs
