### ISSUE TITLE
Support for wordlist-less dns scanning

### ISSUE THREAD

**Issue by leumasme** [OJ/gobuster#404]
Add support for scanning without a wordlist, e.g. I want to scan all alphabetical 4 character subdomains without having to generate a "wordlist" file that contains all possible 4-character strings.

Of course the problem is how configurable this should be (e.g. anything up to n characters, different character set, always add prefix, etc).
A possible way to implement this without having to worry about that would be to let the user specify a regex of all (sub)domains that should be scanned, then use an algorythm/library to iterate the values that satisfy this regex.

**Comment by flashnuke** [comment]
you can achieve the same using crunch to generate the wordlist and then pass it to Gobuster
```bash
crunch 4 4 -t @@@@ -o wordlist.txt  # generates a wordlist of all possible 4 letters lowercase strings
gobuster ...... -w wordlist.txt
```

**Comment by flashnuke** [comment]
I recommend you try `crunch` to generate the wordlist and then pass it to Gobuster
```bash
crunch 4 4 -t @@@@ -o wordlist.txt  # generates a wordlist of all possible 4 letters lowercase strings
gobuster ...... -w wordlist.txt
```

it's fairly easy and quick to use

**Comment by firefart** [comment]
you can even pipe crunch into gobuster and use `-w -` to use stdin as a wordlist. That's the proper way to do this as we won't build wordlist generators inside this tool

**Comment by leumasme** [comment]
Ah, that's good to know!
