### ISSUE TITLE
Excessive error messages

### ISSUE THREAD

**Issue by BetterDefender** [OJ/gobuster#406]
When I do a large scale multi-threaded scan, it generates a lot of error messages, which makes the readability of the scan results poor, I hope the author can handle these error messages or ignore them by specifying parameters, thanks.

Excessive error messages “context deadline exceeded (Client.Timeout exceeded while awaiting headers)”

**Comment by firefart** [comment]
that;s because all your requests time out. Lower your thread rate until you find the sweet spot
