### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by jinzezhi** [OJ/gobuster#407]
![image](https://user-images.githubusercontent.com/93123422/230642356-71c41cc5-f5d9-46d9-b8e5-bf5dadb15724.png)
This problem often occurs, excluding the status code and length will also appear

**Comment by jinzezhi** [comment]
The second question：
![image](https://user-images.githubusercontent.com/93123422/230643506-e5bb9ecb-a0ee-4844-88cd-5fee3af4c4a0.png)

**Comment by jinzezhi** [comment]
Excuse me, is there a solution for this?

**Comment by firefart** [comment]
This is an issue tracker and not an help forum. Also you need to describe what’s wrong in your opinion but if you aren’t able to run —help and figure the obvious problem out yourself I can’t help you either.
