### ISSUE TITLE
Can't see which word of the wordlist actually trigger 

### ISSUE THREAD

**Issue by Bajiio** [OJ/gobuster#412]
I'm using the fuzz mode for a challenge and gobuster find a correct request with my wordlist but, like the attacked field is in the body of POST request, I have no way of seeing wich request succeeded or which word in the wordlist made that request. I don't know if it's normal or not. Is there any way of doing that, or am I just supposed to use another tools ?

![image](https://user-images.githubusercontent.com/60874928/232774234-6e58b38b-e551-410e-8c92-3a19850d6404.png)

**Comment by firefart** [comment]
Thanks I added https://github.com/OJ/gobuster/commit/a7eeac94b71e1077431a37c3d4ae1a7c02e6411d to the dev branch. The location where the word triggered might be a bit trickier based on your options (could be in a header, post body, URL, ...)
