### ISSUE TITLE
Positive status code does not replace the default negative status code

### ISSUE THREAD

**Issue by j123456780** [OJ/gobuster#413]
Hello everyone, I am writing with the time of not knowing if it is a program error or if it is a lack of understanding of how I should use the tool, I hope you can understand me in case I am making a mistake.

![image](https://user-images.githubusercontent.com/109506865/234752835-b2a792ef-de39-4cad-be34-e9747e08a6bd.png)

In this case I am trying to replace the blacklisted code 404 with the positive code 301

according to the help this status should replace the blacklisted

![image](https://user-images.githubusercontent.com/109506865/234752660-84f032de-d777-4f13-8896-568243dcfc28.png)

**Comment by firefart** [comment]
-s 301 only reports urls that respond with 301. I think you want -b 404,301
