### ISSUE TITLE
i/o timeout when use dns mode to enumerate subdomains

### ISSUE THREAD

**Issue by JYThomas** [OJ/gobuster#416]
Hello！ thanks for this amazing tool! Here is the problem when I use gobuster in python script through subprocess, Below is the output, any idea about this problem???

===============================================================
Gobuster v3.5
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Domain:     gxsx.cn
[+] Threads:    50
[+] Show IPs:   true
[+] Timeout:    1s
[+] Wordlist:   ../../dicts/subnames_5000.txt
===============================================================
2023/05/09 21:04:14 Starting gobuster in DNS enumeration mode
===============================================================
2023/05/09 21:04:16 [-] Unable to validate base domain: gxsx.cn (lookup gxsx.cn: i/o timeout)
Progress: 4989 / 4990 (99.98%)
===============================================================
2023/05/09 21:05:56 Finished
===============================================================

**Comment by sk0x1234** [comment]
https://github.com/OJ/gobuster/blob/c3fed5e2f2c4d4b1f3b2643a55d8f0692f49e95d/gobusterdns/gobusterdns.go#L97

its a warning not an error.

**Comment by sk0x1234** [comment]
I'm looking for a option in gobuster dns for do only Type A query not AAAA, is that available yet?
like only get ipv4 IP's not IPv6.

![image](https://github.com/OJ/gobuster/assets/18193527/bccef1af-5983-47cb-8644-ff2594b9a9a0)

**Comment by firefart** [comment]
if your dns requests time out you can try to lower the threads
