### ISSUE TITLE
Attempting to install gobuster latest version on Parrot OS

### ISSUE THREAD

**Issue by rocketsurgeongeneral** [OJ/gobuster#419]
Hey there, I'm reaching out to you because I'm attempting to update gobuster on Parrot OS via the terminal. I've tried running the following commands:

sudo apt-get update
sudo apt-get upgrade gobuster
gobuster version

I currently have 3.1.0 which ChatGPT says is the latest version but it looks like 3.5.0 is the latest?

![Gobuster 3 1 0 on Parrot OS](https://github.com/OJ/gobuster/assets/126862504/580a25fc-2147-4a14-962d-f97ff53f92f9)

**Comment by firefart** [comment]
You need to open an issue on the parrot os tracker as we are not providing those packages
