### ISSUE TITLE
Improvements for dir

### ISSUE THREAD

**Issue by ggt** [OJ/gobuster#422]
Hi, these options should be cool to implement:

- Ability to check if server is case sensitive or not (and skip same requests if it's case insensitive)
- Option to start from a percentage of file ex: 30%
- Possibility to hide timeout error requests with "-b TIMEOUT" by example

Thanks!

**Comment by lautalom** [comment]
> * Option to start from a percentage of file ex: 30%
You mean to start from a percentage of a worldlist? Sounds interesting! I would add also from exact position, e.g. line 33

**Comment by ggt** [comment]
Yes, exact line or exact word, check for duplicates too... :)

**Comment by firefart** [comment]
there is a wordlist offset option in the dev branch already
