### ISSUE TITLE
Incorporating a flag to choose words with certain length

### ISSUE THREAD

**Issue by AnisTigrini** [OJ/gobuster#435]
Hi there hope you are well !
Would anyone consider putting a flag to choose only words with a certain length when using a wordlist ?
I though it would be a cool feature (mainly for CTF).

**Comment by firefart** [comment]
you can use the stdin wordlist feature for this like
```bash
grep -oE '\b.{9}\b' wordlist | gobuster dir -u xxxx -w -
```
We will not add flags to mangle the input wordlist to keep it simple
