### ISSUE TITLE
Error: unknown flag: --wildcard

### ISSUE THREAD

**Issue by mhmmuneef** [OJ/gobuster#438]
when i run  the command line `gobuster dir -u http://127.0.0.1 -w /usr/share/wordlists/disbuster/director-list-2.3-medium.txt --wildcard `getting error message 

`Error: unknown flag: --wildcard`

why is that ?

**Comment by firefart** [comment]
because there is no wildcard flag. use the —help

**Comment by mhmmuneef** [comment]
thanks
