### ISSUE TITLE
Show the path when timeout

### ISSUE THREAD

**Issue by iselt** [OJ/gobuster#441]
Sometimes it's a big file which causes timeout but we can't see the path. 
![图片](https://github.com/OJ/gobuster/assets/101086473/0ec05052-e50b-4abf-8321-5ec0dab1893c)

I modified the the code to show the path but it's not elegant: https://github.com/iselt/gobuster
![图片](https://github.com/OJ/gobuster/assets/101086473/e36e1e60-03fa-43bd-8d18-48a7b896105e)

Hope you can add the function officially.

**Comment by iselt** [comment]
PS: Because of multi-thread, you can't find the path by the progress number.

**Comment by firefart** [comment]
this is already implemented on the dev branch. You can try it with go install github.com/OJ/gobuster/v3@dev
