### ISSUE TITLE
MTLS not working

### ISSUE THREAD

**Issue by gl4nce** [OJ/gobuster#443]
Unfortunately, MTLS is not working for me. I'm getting `Error: error on parsing arguments: could not load P12: pkcs12: unknown digest algorithm: 2.16.840.1.101.3.4.2.1`.

I did little research and looks like it has something to do with go/security? I'm using version `3.6.0-0kali1`.

```
gobuster dir -u "https://web.site" -w /usr/share/wordlists/dirb/big.txt --client-cert-p12 ./mtls.p12 --client-cert-p12-password "password123"
Error: error on parsing arguments: could not load P12: pkcs12: unknown digest algorithm: 2.16.840.1.101.3.4.2.1
```

**Comment by gl4nce** [comment]
I found a workaround. Converting p12 to pem format with openssl works fine.

```
# converting
openssl pkcs12 -in mtls.p12 -out mtls.crt.pem -clcerts -nokeys
openssl pkcs12 -in mtls.p12 -out mtls.key.pem -nocerts -nodes

# gobuster
gobuster dir -u "https://web.site" -w /usr/share/wordlists/dirb/big.txt --client-cert-pem ./mtls.crt.pem --client-cert-pem-key ./mtls.key.pem
```

**Comment by firefart** [comment]
Jeah looks like this is a problem with gos implementation of pkcs12. There is already an open issue for this:
https://github.com/golang/go/issues/62375

**Comment by firefart** [comment]
Looks like hashicorp switched to another library because of this problem: https://github.com/hashicorp/go-azure-sdk/pull/328
will have a look if the other library works too

**Comment by firefart** [comment]
@gl4nce can you please try out the dev branch and if that works for your p12?
`go install github.com/OJ/gobuster/v3@dev`

Thanks!

**Comment by firefart** [comment]
Awesome thanks for testing :)
