### ISSUE TITLE
[fuzz]  [fe80::1%wlp2s0]:53: server misbehaving

### ISSUE THREAD

**Issue by CyberShadow7** [OJ/gobuster#465]
I noticed an ERROR message similar to issue#128 on this page where I get the following error : 
`[ERROR] 2023/11/13 18:11:45 [!] Get "https://*redacted*": dial tcp: lookup *redacted* on [fe80::1%wlp2s0]:53: server misbehaving`

I am running gobuster on Linux 6.1.0 amd64 and have the latest version of gobuster at the time of writing.

Any tips that could help me:
1. Understand the error message
2. Solve this error message

On another note none of my hardware components spike during the fuzz test (only using 10 threads does not solve the issue either; maybe it delays it, 50 threads I get results but also a spam of this error message) and Network,RAM,Cache,CPU usage is minimal.

Thank you in advance!

**Comment by firefart** [comment]
The error indicates that your dns server returned an error or an unexpected response when looking up the hostname. You can try reducing the threads to see if it’s a load based problem on the dns server
