### ISSUE TITLE
[New functionnality] - Insensitive option

### ISSUE THREAD

**Issue by ggt** [OJ/gobuster#466]
Hi,
  First, thanks to have added the option for restarting at an offset!

I think if you have the time, a new good option should be implemented: "-i // insensitive search" to brute-force from a "dict" file and removes duplicate searchs automatically. This options should be cool because we won't have to have multiple files with the same data [a-Z] and [a-z].

Thanks!

**Comment by firefart** [comment]
That's not really possible as we would need to keep track of every word processed in memory and that would result in enormous memory usage. The best solution for this usecase is to use the stdin wordlist feature like

```
cat wordlist1 wordlist2 wordlist 3 | sort -u | gobuster dir -w - ....
```
