### ISSUE TITLE
Is it possible to scan domain like https://pubaccount10086.blob.core.windows.net?

### ISSUE THREAD

**Issue by supasaf** [OJ/gobuster#467]
I just found gobuster, it's great!

In order to test gobuster, I created an Azure storage account, set it to public and uploaded a tmp.txt file to it, so basically we can access the file from: https://pubaccount10086.blob.core.windows.net/ftest/tmp.txt

<img width="480" alt="image" src="https://github.com/OJ/gobuster/assets/147785346/19b441b2-6c98-4669-937b-f2342c5a8ca2">

I created another file for testing:

```
❯ cat subnames.txt
pubaccount
```

With command:

```
❯ gobuster dns -d blob.core.windows.net -w subnames.txt --wildcard
===============================================================
Gobuster v3.6
by OJ Reeves (@TheColonial) & Christian Mehlmauer (@firefart)
===============================================================
[+] Domain:            blob.core.windows.net
[+] Threads:           10
[+] Wildcard forced:   true
[+] Timeout:           1s
[+] Wordlist:          subnames.txt
===============================================================
Starting gobuster in DNS enumeration mode
===============================================================
Progress: 1 / 2 (50.00%)
Found: pubaccount.blob.core.windows.net

===============================================================
Finished
===============================================================
```

It sounds like subdomains like `pubaccount10086` can't be found, not sure if I missed something?

**Comment by firefart** [comment]
it can find everything you put in your wordlist. if you don’t put it in your wordlist, it won’t be reported
