### ISSUE TITLE
Not able to perform directory enumerations

### ISSUE THREAD

**Issue by Prajwal-PS7** [OJ/gobuster#468]
getting an error while performing the Fuzzing test for directory 

Used command ;

 **$ gobuster dir --url http://localhost/ -t 100 -w wordlist.txt -o result.txt**

`Error: the server returns a status code that matches the provided options for non existing urls. http://localhost/2f147774-1c39-4730-ae27-5d5c00b0fcab => 301 (Length: 167). To continue please exclude the status code or the length`

Also 

**$ gobuster fuzz --url http://localhost/FUZZ -t 100 -w wordlist.txt -o result.txt**

`Error: the server returns a status code that matches the provided options for non existing urls. http://localhost/2f147774-1c39-4730-ae27-5d5c00b0fcab => 301 (Length: 167). To continue please exclude the status code or the length`

any solution for this?

**Comment by firefart** [comment]
the solution is shown in the error message

**Comment by Prajwal-PS7** [comment]
i try those also but same error showing!

**Comment by firefart** [comment]
then you might need to exclude more lengths. There is no way for gobuster to determine a hit if every 404 and 200 respond the same, that's why you need to exclude the length or status code

**Comment by Prajwal-PS7** [comment]
i did it by passing -z <max_length> flag, but no luck!

**Comment by firefart** [comment]
there is no -z parameter, use —help to show all available options
