### ISSUE TITLE
Add `--exclude-dir` on dir mode

### ISSUE THREAD

**Issue by KeepWannabe** [OJ/gobuster#476]
I think this feature would be great, 

because when i try to bruteforce the directory with **logged-in** conditions, it will **logged-out** if i hit the `/login` route.
so for avoid this kind of problem, adding the `--exclude-dir/path` is awesome.

**Comment by firefart** [comment]
you can modify the wordlist to exclude the words. Just do a `grep -v` and pipe it as stdin to gobuster and use `-w -`
