### ISSUE TITLE
TEST FAILURE: -buildmode=pie not supported when -race is enabled on linux/amd64

### ISSUE THREAD

**Issue by blshkv** [OJ/gobuster#512]
don't know much about it, but you might have some ideas:
```
>>> Test phase: net-analyzer/gobuster-3.6.0
make -j8   test
go test -v -race ./...
-buildmode=pie not supported when -race is enabled on linux/amd64
make: *** [Makefile:25: test] Error 1
```
Also, see:
https://github.com/pentoo/pentoo-overlay/issues/1814

**Comment by firefart** [comment]
Just remove the -race flag or also build with -race before. This is not supported in go:
https://go-review.googlesource.com/c/go/+/41335
If you need a release binary just remove the -race flag from the tests

**Comment by blshkv** [comment]
Please remove it in your Makefile:
https://github.com/OJ/gobuster/blob/master/Makefile#L25

**Comment by firefart** [comment]
Why should I? You are building it on your machine, just execute the command

**Comment by blshkv** [comment]
I'm just executing it : "make test" and fails. Isn't the problem in the Makefile?
