### ISSUE TITLE
status-codes-blacklist

### ISSUE THREAD

**Issue by sec13b** [OJ/gobuster#518]
gobuster dir -u http://10.155.100.10/ -w /usr/share/dirbuster/wordlists/directory-list-2.3-medium.txt -s '200,204,301,302,307,403,404,500' -e -x txt,html,php,asp

Error: error on parsing arguments: status-codes ("200,204,301,302,307,403,404,500") and status-codes-blacklist ("404") are both set - please set only one. status-codes-blacklist is set by default so you might want to disable it by supplying an empty string.

how i correct this ?

**Comment by firefart** [comment]
`gobuster dir -u http://10.155.100.10/ -w /usr/share/dirbuster/wordlists/directory-list-2.3-medium.txt -s '200,204,301,302,307,403,404,500' -b '' -e -x txt,html,php,asp`
