### ISSUE TITLE
Show destination when 'wildcard response found'

### ISSUE THREAD

**Issue by 0xdevalias** [OJ/gobuster#52]
Currently when a wildcard response is found it looks something like this:
```
[-] Wildcard response found: https://example.com/47ebafdb-032d-4a47-bf41-26b1a4314326 => 302
```

It would be useful if the destination URL was shown as well, maybe something like:
```
[-] Wildcard response found: https://example.com/47ebafdb-032d-4a47-bf41-26b1a4314326 => 302 => https://example.com/foo
```

This comes from:
https://github.com/OJ/gobuster/blob/7a6d1c068e3e89ee9b3c0c01cb3946957143a0c9/main.go#L565

Currently `GoGet` appears to just be returning the status code and content size, so changes would need to be made there, and to `MakeRequest`

https://github.com/OJ/gobuster/blob/7a6d1c068e3e89ee9b3c0c01cb3946957143a0c9/main.go#L228-L230

https://github.com/OJ/gobuster/blob/7a6d1c068e3e89ee9b3c0c01cb3946957143a0c9/main.go#L223

**Comment by firefart** [comment]
this is already implemented in the dev branch for dir mode
