### ISSUE TITLE
Minimize content downloaded for each checked URL

### ISSUE THREAD

**Issue by 0xdevalias** [OJ/gobuster#53]
I haven't confirmed this, but the feel I got from looking at the code is that currently gobuster downloads the entire page for each checked URL.

If that is the case, there are a few methods I was thinking of that may help to speed this up:
* Using the range header: https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
* Supporting HEAD/OPTIONS requests (https://github.com/OJ/gobuster/pull/44)

On the topic of using the range header, it could be that some tests are done at the beginning to see if it is supported (similar to the 'wildcard response found' check) to ensure the server supports ranges.

If there is support for it, gobuster could send the range header to limit the request to a reasonably small size (maybe customizable from flags with a sensible default)

If it's not supported by the server, maybe gobuster could forcibly close the connection after reading X bytes as a fallback.

If there isn't already a timeout set for a connection that 'never returns', that could be implemented in a similar way, again customisable.

There may be other optimisations that could be done in a similar vain to this, but for now, these are the ones coming to mind.

**Comment by mzpqnxow** [comment]
@0xdevalias I would caution against using HEAD as there are many common server configurations that either explictly reject HEAD, reject it silently with a 404, or behave in some otherwise misleading way, leading mainly to false negatives.

Just my $.02

**Comment by 0xdevalias** [comment]
Yeah, that is definitely a good point. I’d sort of half considered it, but probably didn’t really articulate that.

**Comment by FireFart** [comment]
You can now specify a custom http verb in the `v3.1-cleaned` branch so I classify this as done :)
