### ISSUE TITLE
i need create names.txt fie ? i install it now and get this error . thanks

### ISSUE THREAD

**Issue by GreenAA** [OJ/gobuster#537]
\pkg\mod\github.com\!o!j\gobuster\v3@v3.6.0>gobuster dns -d mysite.com -t 50 -w common-names.txt
Error: error on parsing arguments: wordlist file "common-names.txt" does not exist: CreateFile common-names.txt: The system cannot find the file specified.

**Comment by firefart** [comment]
please read the error

**Comment by GreenAA** [comment]
thanks bro .. i create file txt. 
 hhh .. sorry

**Comment by GreenAA** [comment]
![Screenshot 2024-11-07 203649](https://github.com/user-attachments/assets/82fcb26f-af23-4273-a87b-09dd52174aa7)

hi bro i put the common-names.txt file in the C:\Users\7\go\pkg\mod\github.com\!o!j\gobuster\v3@v3.6.0

so why i get massage 
Error: error on parsing arguments: wordlist file "common-names.txt" does not exist: CreateFile common-names.txt: The system cannot find the file specified.


thanks
