### ISSUE TITLE
Add HTTP Size Support for 301/302 Requests

### ISSUE THREAD

**Issue by IppSec** [OJ/gobuster#57]
Currently HTTP Response size of Redirects is not displayed, even with the -l flag in Directory Mode.  I'm not sure how common it is in the real world, but I've come across several CTF Machines that unintentionally expose PHP Scripts by forgetting to call exit() after HTTP Redirect. 

This is the only reason I'd prefer to use DirBuster over the command line alternatives (GoBuster/Dirb).  I'd love to recommend GoBuster as its CLI Driven, Faster, and more reliable however I really dislike the lack of response since on the 301/302 requests.

**Comment by IppSec** [comment]
This appears to be due to the HTTP Redirect being classified as an Error.

**Comment by OJ** [comment]
Are you able to confirm this is still an issue with 2.0.0 ?

**Comment by FireFart** [comment]
closing due to lack of response
