### ISSUE TITLE
add more than one dictionary? -w?

### ISSUE THREAD

**Issue by r3k2** [OJ/gobuster#58]
Hello is there a way to add more than one dictionary? I tried -w dic.txt,dic2.txt also with -w dic.txt -w dict2.txt with no luck
Also recursive in most cases sucks.. but is not to have the option in case is needed...

**Comment by OJ** [comment]
Hi @ChrisFernandez,

The easy way is `cat` and pip, like this:
```
$ cat dic.txt dic2.txt | gobuster ...
```

As far as recursive goes, I won't be adding it. Soon I'll be writing a wiki page that will explain why. I've even had an [issue open for a while](https://github.com/OJ/gobuster/issues/40) to remind me :) Thanks!

**Comment by ChrisFernandez** [comment]
oh true.. thanks.

**Comment by ChrisFernandez** [comment]
Hello sorry did not had time to try this until now.. the apps exits if a -w is not passed
=====================================================
[!] WordList (-w): Must be specified

so the stdin is not working
Gobuster v1.3

**Comment by OJ** [comment]
Hi @ChrisFernandez, I'm sorry to hear that. Leave this with me and I'll see what's going on. It _should_ work. Would you mind giving me the platform you're running it on?

Thank you.

PS. Short term fix is catting all the wordlists together.. but yeah not idea. Sorry!

**Comment by ChrisFernandez** [comment]
@OJ hey no problem, I'm happy to help find bugs. I am using Arch GNU/Linux 
example command:
```
[ blackarch comandos ]$ cat ~/herramientas/diccionarios/SecLists/Discovery/Web_Content/common.txt | gobuster  -t 300 -s 200,204,301,302,307,403,500  -u http://192.168.1.10

Gobuster v1.3                OJ Reeves (@TheColonial)
=====================================================
[!] WordList (-w): Must be specified
=====================================================
```

Hope this helps.

**Comment by rsrdesarrollo** [comment]
Another workaround, use process substitution:

gobuster  -t 300 -s 200,204,301,302,307,403,500  -u http://192.168.1.10 -w **<(cat ~/herramientas/diccionarios/SecLists/Discovery/Web_Content/common.txt )**

**Comment by telboon** [comment]
I'm interested to do a PR to add the feature to have multiple wordlists. It will require recursion on the wordlists though, so what do you think?

**Comment by FireFart** [comment]
I also had some troubles with STDIN especially when called from within bash files. That's why I reworked the stdin logic here https://github.com/OJ/gobuster/pull/79 if you want to give it a try (pass `-` to `-w` parameter). Installation instructions to get the changes to your local gobuster installation are also included in the PR description.

**Comment by FireFart** [comment]
this should work now (`v3.1-cleaned` branch)
