### ISSUE TITLE
Rework CLI into cobra

### ISSUE THREAD

**Issue by 0xdevalias** [OJ/gobuster#59]
While it might add a slight bit more size to the binary, I think the flexibility/ease of implementation we can get from using a more full featured CLI would be pretty sweet.

https://github.com/spf13/cobra is used by a huge number of go projects, and is really nice to work with from my little experience.

I think this could work into the stuff already landing (referenced from #55) with the refactor, and make a nice little rework for 1.4.

Would you be open to it @OJ ?

**Comment by kkirsche** [comment]
Is this of interest?

**Comment by OJ** [comment]
I'd definitely be open to this. I just used the built-in features to begin with as part of my "how to do stuff poorly with Go" project. I'm absolutely open to improvements, and if this is an area that will benefit then I say "let's do it". I'm happy to learn :)

**Comment by OJ** [comment]
I'm at the point with the existing merges where there's a lot of code divergence. I'm still thinking that we should go with the removal of the idea of `libgobuster` and just having `gobuster` as we did before. So I'll probably revert back to that while still having it as a reusable library.

**Comment by OJ** [comment]
Anyway, my feeling here is "can we please hold off on another PR until 1.4 is landed".

We'll look to get this new CLI in for the next release?

**Comment by 0xdevalias** [comment]
I think making `libgobuster` just `gobuster`, and then the CLI command would be `gobuster/cmd/gobuster` would be the best idea. That'll align with the cobra directory layout as well I believe.

I agree that not trying to land any new changes until 1.4 is finalised (or at the very least, to a stable enough point of refactoring that new PR's can be based off that branch)

Do we have a rought ETA on 1.4.x?

**Comment by OJ** [comment]
https://github.com/OJ/gobuster/milestone/4 :)

**Comment by FireFart** [comment]
This has been implemented in v3
