### ISSUE TITLE
Add recursive option

### ISSUE THREAD

**Issue by kawaxi** [OJ/gobuster#62]
Hi, thanks for your work.!

It would be really nice to have an option for recursive scan when looking for folders so I don't have to do it manually. 
 
So when you have something like : 
http://foo/foophones/category  
http://foo/foophones/images

You could also find out the following with the new function
http://foo/foophones/images/products
http://foo/foophones/images/avatars

Thanks.

**Comment by 0xdevalias** [comment]
@OJ has answered this a few times before in issues (can't find any to reference off hand) and has said he intends to write up his rationale in the README at some point, but basically, this isn't a feature that he wants, or intends to implement (at least the last time I checked)

The README currently makes brief mention to this in point 3 of:
* https://github.com/OJ/gobuster#oh-dear-god-why

**Comment by kawaxi** [comment]
That's sad to hear... Thanks for your time @0xdevalias

**Comment by OJ** [comment]
I promise I'll write up my rationale soon :)

**Comment by kawaxi** [comment]
thanks for your time @OJ , it could be activated with a flag so it won't be recursive all the time. just saying ..

thanks again.

**Comment by OJ** [comment]
You make it sound so simple ;)

**Comment by void-m4110c** [comment]
Well...some years have passed. Is there any progress on the "rationale"?
