### ISSUE TITLE
Use contexts to handle termination

### ISSUE THREAD

**Issue by kkirsche** [OJ/gobuster#63]
I noticed that you were using a boolean for the termination in state:

https://github.com/OJ/gobuster/blob/1.4-dev/libgobuster/state.go#L69

Have you considered using contexts instead? 

https://golang.org/pkg/context/

An example is in the implementation I did based on your library.

The thread which receives the "Done" message:
https://github.com/kkirsche/gbust/blob/master/libgbust/worker.go#L18

The main context creation. The cancel is a context.CancelFunc which allows you to tell everything using it to "finish" what it's doing:
https://github.com/kkirsche/gbust/blob/master/libgbust/attacker.go#L74

**Comment by FireFart** [comment]
Implemented in this PR https://github.com/OJ/gobuster/pull/79

**Comment by OJ** [comment]
Doneski!
