### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by JohnnyAMD** [OJ/gobuster#7]
Hi, 

Just had a try of your toy but first compile action gave me an error. 

"./main.go:286: undefined: bufio.NewScanner"

Platform: Kali 64 bit. 
go compiler installed by using "apt-get install golang"

Any ideas of how that can be resolved?

The NewScanner directive is located only with that line, 286, so I suppose you would know better what's going on at that point. 

Thanks.

**Comment by OJ** [comment]
This won't build on Kali with the default go setup. You'll have to install a more up-to-date go environment.

Either that or build it on another machine :) But yeah, Kali is your problem. Cheers!

**Comment by OJ** [comment]
To be clear, I meant that you needed to download and install the go tools from golang.org or through a more up to date deb package. The one in the Kali repo is outdated. Thanks!

**Comment by g0tmi1k** [comment]
For what its worth:

+ Kal 1.x was based on Debian 7 - uses go 1.0
+ Kal 2.x is based on Debian 8 - uses go 1.3


## Kali 1
```
root@kali:~/gobuster# go build
# _/root/gobuster
./main.go:286: undefined: bufio.NewScanner
root@kali:~/gobuster#
```

## Kali 2
```
root@kali:~/gobuster# go build
root@kali:~/gobuster# ./
.git/     gobuster  
root@kali:~/gobuster# ./gobuster 
WordList (-w): Must be specified
Url/Domain (-u): Must be specified
root@kali:~/gobuster# go version
go version go1.3.3 linux/amd64
root@kali:~/gobuster#
```

**Comment by OJ** [comment]
Thanks @g0tmi1k :)

**Comment by JohnnyAMD** [comment]
Thanks @g0tmi1k. I got it installed over a Ubuntu 14 LTS VM and is working properly right now :)
