### ISSUE TITLE
Progress Bar Feature & Verbose Resume

### ISSUE THREAD

**Issue by Mteor** [OJ/gobuster#78]
Hello!
I find this tool pretty good, so well done!
There are two features that if you could add, it would help a lot.
* Having a progress bar/percentage status would be good. For very big wordlists, the user doesnt have a way to know how far the scanning is from the end.
* When using verbose mode, the tool should save in a dictionary for example, all requests with relevant status codes, and print them in the end. So one doesnt have to scroll over the screen to find relevant status.

Also, tell me what you think of these.
Thank you.

**Comment by FireFart** [comment]
First example of progress implemented here:
https://github.com/OJ/gobuster/pull/79

**Comment by OJ** [comment]
We don't have pause/resume, but we do have progress. I'm going to close this off now and I'll open another to talk about pause/resume. etc.
