### ISSUE TITLE
no I/O exception handling

### ISSUE THREAD

**Issue by AddaxSoft** [OJ/gobuster#80]
When webserver block gobuster from brute forcing files, gobuster doesn't have the proper I/O exception handling and will just hang forever.

even if you ctr+c to interrupt it won't respond

**Comment by codingo** [comment]
@AddaxSoft in the meantime (whilst @FireFart is working on this) you could pipe results to [tee](https://en.wikipedia.org/wiki/Tee_(command)).

**Comment by OJ** [comment]
This should be good now :) Thanks.
