### ISSUE TITLE
stdin detection fails to detect pipes vs. redirected stdin in various situations

### ISSUE THREAD

**Issue by tomnomnom** [OJ/gobuster#84]
Hello! Great tool!

I've come across a couple of situations where the stdin detection breaks.

The first situation is: gobuster works using `< filename` style IO redirection:

```
▶ gobuster -u "https://www.google.com/" -q < wordlist.txt
/robots.txt (Status: 200)
```

But not if the input comes from a pipe:

```
▶ cat wordlist.txt | gobuster -u "https://www.google.com/" -q
1 error occurred:

* [!] WordList (-w): Must be specified
```

The second situation is kind of the reverse. When in a bash while loop fed using IO redirection, and a wordlist is specified with `-w`, gobuster erroneously attempts to read the wordlist from the file being fed to the while loop and fails:

```
▶ while read url; do gobuster -u "$url" -q -w wordlist.txt; done < urls.txt
1 error occurred:

* [!] Wordlist (-w) specified with pipe from stdin. Can't have both!
```

This doesn't happen when the while loop is being fed with a pipe (because the size of the stdin device is zero, which is checked for [here](https://github.com/OJ/gobuster/blob/34c7157f60013198d862efa43a1024d4617df51d/libgobuster/statehelpers.go#L70)):

```
▶ cat urls.txt | while read url; do gobuster -u "$url" -q -w wordlist.txt; done
/robots.txt (Status: 200)
```

I think this is a difficult problem to tackle because of the various different permutations in which the tool can be run. One option is to avoid doing stdin detection at all, and allow people to specify `-w -` to force reading the wordlist from stdin; it's not something that is without precedent, but it does add a little something extra for the user.

Another option is to always use a wordlist if one is specified with `-w`, and only attempt to read from stdin if none is specified. This option has the downside that the command will hang if the user forgets the `-w` option but provides no words on stdin.

**Comment by FireFart** [comment]
@tomnomnom I encountered the same behaviour before and changed it in this PR: https://github.com/OJ/gobuster/pull/79
It's not merged yet, but the wordlist parameter now takes a `-` as a value to read from stdin. If you want to try the updated version there are test instructions in the pull request

**Comment by tomnomnom** [comment]
Ah super! I'll close this issue in that case :) Thanks!
