### ISSUE TITLE
Replace package satori/go.uuid

### ISSUE THREAD

**Issue by josselin-c** [OJ/gobuster#87]
This issue has been opened automaticaly because we think you are using satori/uuid in your code. Unfortunately, satori/uuid has a critical defect where it doesn't generate random UUIDV4s satori/go.uuid#73 and should be replaced as the maintainer has been unresponsive for 5 months with the bug still open. Alternative packages you should consider: https://github.com/google/uuid https://github.com/pborman/uuid

**Comment by FireFart** [comment]
Thanks! I replaced the package in this PR https://github.com/OJ/gobuster/pull/79

**Comment by josselin-c** [comment]
That was fast 👍

**Comment by OJ** [comment]
Thanks FireFart, but please don't make that PR any bigger! Please! :)

**Comment by OJ** [comment]
This should be good now. Thanks.
