### ISSUE TITLE
Some usefull feature requests

### ISSUE THREAD

**Issue by ThatDarkAngel** [OJ/gobuster#90]
Hello,
Just started using gobuster. For me it seems some of usefull features still missing.
Here is they are:
1) Pause and Resume actions. (I know i can simply CTRL+Z and fg)
2) Exclude by response size. Like wfuzz does it flawlessly. That would be really great implement something like this:
--filter="(c!=404 and l!=1000)"   (where c eq status code and l eq response length.)
BTW, wfuzz supports logical operators.

Thank you!

**Comment by OJ** [comment]
Hi,

Thanks. Both of these features are in active discussion or development in other issues. I won't be implementing a full search feature, but you will be able to filter based on status (which is done already), inverse status (PR waiting to land) and ranges of response sizes.

Thanks.
