### ISSUE TITLE
progress bar is not working in new version

### ISSUE THREAD

**Issue by carnal0wnage** [OJ/gobuster#91]
Progress bar isnt moving during the wordlist run

```
$ ./gobuster -w wordlist/cg_big_wordlist.txt -u yahoo.com -m dns -t 10 -i
=====================================================
Gobuster v2.0.0              OJ Reeves (@TheColonial)
=====================================================
[+] Mode         : dns
[+] Url/Domain   : yahoo.com
[+] Threads      : 10
[+] Wordlist     : wordlist/cg_big_wordlist.txt
=====================================================
2018/08/29 21:09:38 Starting gobuster
=====================================================
Found: 360.yahoo.com [98.136.96.140, 98.136.101.175, 2001:4998:44:3204::1000, 2001:4998:24:705::3000]
Found: 3d.yahoo.com [98.136.103.23]
Progress: 0 / 97371 (0.00%)
```

let the whole thing run and stayed at progress 0 :-(

**Comment by FireFart** [comment]
did it finish?

**Comment by FireFart** [comment]
Oh I see the problem here, `incrementRequests` is never called in DNS mode so the counter is never updated

**Comment by OJ** [comment]
Bahahaha!

Oops.

Common problem I've noticed is that many people user this tool for one more
or the other. Only very few use it for both.

I can get this fixed quickly.

@FireFart shouldn't those counters be updated outside of the plugins so the
code doesn't need to be repeated?

**Comment by FireFart** [comment]
It's currently called inside libgobuster https://github.com/OJ/gobuster/blob/master/libgobuster/libgobuster.go#L114 so plugins do not have to care about this. Also incrementRequests is not exported so it's not callable from plugins. I think it would be best to invoke it just before Process() is called. I will have a look into it

**Comment by OJ** [comment]
My feeling is that the [GetRequest](https://github.com/OJ/gobuster/blob/master/libgobuster/libgobuster.go#L111-L116) function should be pushed into the dir plugin.

I think we should also have the requests incremented as soon as a word has been thrown down the channel [here](https://github.com/OJ/gobuster/blob/master/libgobuster/libgobuster.go#L207). This keeps the progress counting in `libgobuster`. Thoughts?

**Comment by OJ** [comment]
Oops! Fat-fingered closing the issue, sorry!

**Comment by OJ** [comment]
Fixificated! Thanks @carnal0wnage for the report and @FireFart for the fix.

@FireFart keen to do a bit of a refactor around here, will chat to you behind the scenes.
