### ISSUE TITLE
Feature Request - Silence warnings

### ISSUE THREAD

**Issue by Rhynorater** [OJ/gobuster#96]
Is there some way you can silence these [!] warnings? They make the output pretty unreadable and I usually get a lot of them. 

Thanks!

**Comment by FireFart** [comment]
If you mean errors: yes
https://github.com/OJ/gobuster/blob/master/main.go#L79
Just supply the quiet flag. Does this solve your problem?

**Comment by Rhynorater** [comment]
That's what I've been using, but I still like to see that intro piece. Silencing errors would be a great option.

**Comment by kildonan5** [comment]
The quiet flag supresses progress, which is great improvement on previous versions. It would be nice to surpress the warnings, even while still showing progress. Perhaps consider making the warnings show up when verbose mode is on?

**Comment by FireFart** [comment]
I think we should write the warnings to stderr in the future to have an option to remove them by `2 > /dev/null`

**Comment by FireFart** [comment]
Just had a look and all errors are already output to stderr so you should be able to silence them by redirecting stderr to /dev/null
