### ISSUE TITLE
[issue] Progress Bar

### ISSUE THREAD

**Issue by its0x08** [OJ/gobuster#97]
Hello 
sorry for disturbing..
progress feature doesn't seem to work for me using the latest version in Kali.
Linux kaLi 4.17.0-kali3-amd64 #1 SMP Debian 4.17.17-1kali1 (2018-08-21) x86_64 GNU/Linux
go version go1.10.3 linux/amd64
Thanks

**Comment by FireFart** [comment]
what do you mean by "it's not working"? What's your installed gobuster version and what is the output you see vs the output you expected?

**Comment by its0x08** [comment]
Gobuster v2.0.0              OJ Reeves (@TheColonial)

what I see:  Progress: 0 / 100001 (0.00%)
what I expect to see: Progress: 1000 / 100001 (1.00%)

It never updates..it stays same all the time ..

**Comment by OJ** [comment]
Fixed in 2.0.1.
